-- Base CENTRALE de Pelote Manager uniquement.
-- Cette migration ne doit jamais être appliquée dans une instance de club.

begin;

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid null references auth.users(id) on delete set null
);

create table if not exists public.platform_clubs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  contact_email text null,
  subscription_plan text not null default 'standard',
  status text not null default 'provisioning'
    check (status in ('provisioning', 'trial', 'active', 'suspended', 'cancelled')),
  supabase_project_ref text null unique,
  supabase_url text null,
  vercel_project_name text null unique,
  deployment_url text null,
  current_version text null,
  target_version text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict
);

create table if not exists public.platform_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_club_id uuid null references public.platform_clubs(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists platform_clubs_status_idx
  on public.platform_clubs (status, name);

create index if not exists platform_audit_log_target_idx
  on public.platform_audit_log (target_club_id, created_at desc);

alter table public.platform_admins enable row level security;
alter table public.platform_clubs enable row level security;
alter table public.platform_audit_log enable row level security;

create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.platform_admins as admins
    where admins.user_id = auth.uid()
      and admins.is_active
  );
$$;

create policy "platform admins read their access"
on public.platform_admins
for select
to authenticated
using (public.is_platform_admin());

create policy "platform admins read clubs"
on public.platform_clubs
for select
to authenticated
using (public.is_platform_admin());

create policy "platform admins read audit"
on public.platform_audit_log
for select
to authenticated
using (public.is_platform_admin());

create or replace function public.platform_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_platform_admin();
$$;

create or replace function public.platform_list_clubs()
returns table (
  id uuid,
  name text,
  slug text,
  contact_email text,
  subscription_plan text,
  status text,
  supabase_project_ref text,
  supabase_url text,
  vercel_project_name text,
  deployment_url text,
  current_version text,
  target_version text,
  notes text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Accès refusé' using errcode = '42501';
  end if;

  return query
  select
    clubs.id,
    clubs.name,
    clubs.slug,
    clubs.contact_email,
    clubs.subscription_plan,
    clubs.status,
    clubs.supabase_project_ref,
    clubs.supabase_url,
    clubs.vercel_project_name,
    clubs.deployment_url,
    clubs.current_version,
    clubs.target_version,
    clubs.notes,
    clubs.created_at,
    clubs.updated_at
  from public.platform_clubs as clubs
  order by clubs.name;
end;
$$;

create or replace function public.platform_create_club(
  new_name text,
  new_slug text,
  new_contact_email text default null,
  new_subscription_plan text default 'standard',
  new_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_club_id uuid;
  normalized_slug text;
begin
  if not public.is_platform_admin() then
    raise exception 'Accès refusé' using errcode = '42501';
  end if;

  normalized_slug := lower(trim(new_slug));

  if nullif(trim(new_name), '') is null then
    raise exception 'Le nom du club est obligatoire' using errcode = '22023';
  end if;

  if normalized_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
    raise exception 'Le slug est invalide' using errcode = '22023';
  end if;

  if new_subscription_plan not in ('standard', 'premium', 'custom') then
    raise exception 'La formule est invalide' using errcode = '22023';
  end if;

  insert into public.platform_clubs (
    name,
    slug,
    contact_email,
    subscription_plan,
    notes,
    created_by
  ) values (
    trim(new_name),
    normalized_slug,
    nullif(lower(trim(new_contact_email)), ''),
    new_subscription_plan,
    nullif(trim(new_notes), ''),
    auth.uid()
  )
  returning id into created_club_id;

  insert into public.platform_audit_log (
    actor_user_id,
    action,
    target_club_id,
    details
  ) values (
    auth.uid(),
    'club.created',
    created_club_id,
    jsonb_build_object(
      'name', trim(new_name),
      'slug', normalized_slug,
      'subscription_plan', new_subscription_plan
    )
  );

  return created_club_id;
end;
$$;

create or replace function public.platform_update_club_status(
  target_club_id uuid,
  new_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_platform_admin() then
    raise exception 'Accès refusé' using errcode = '42501';
  end if;

  if new_status not in ('provisioning', 'trial', 'active', 'suspended', 'cancelled') then
    raise exception 'Le statut est invalide' using errcode = '22023';
  end if;

  update public.platform_clubs
  set status = new_status,
      updated_at = now()
  where id = target_club_id;

  if not found then
    raise exception 'Club introuvable' using errcode = 'P0002';
  end if;

  insert into public.platform_audit_log (
    actor_user_id,
    action,
    target_club_id,
    details
  ) values (
    auth.uid(),
    'club.status_updated',
    target_club_id,
    jsonb_build_object('status', new_status)
  );
end;
$$;

revoke all on function public.is_platform_admin() from public, anon, authenticated;
revoke all on function public.platform_is_admin() from public, anon, authenticated;
revoke all on function public.platform_list_clubs() from public, anon, authenticated;
revoke all on function public.platform_create_club(text, text, text, text, text)
  from public, anon, authenticated;
revoke all on function public.platform_update_club_status(uuid, text)
  from public, anon, authenticated;

grant execute on function public.platform_is_admin() to authenticated;
grant execute on function public.platform_list_clubs() to authenticated;
grant execute on function public.platform_create_club(text, text, text, text, text)
  to authenticated;
grant execute on function public.platform_update_club_status(uuid, text)
  to authenticated;

commit;
