export const ROUTES = {
  home: "/",
  login: "/connexion",
  register: "/inscription",
  reservations: "/reservations",
  myReservations: "/mes-reservations",
  reservationPaymentReturn: "/reservations/paiement",
  tournaments: "/tournois",
  admin: "/admin",
  adminUsers: "/admin/utilisateurs",
  adminReservations: "/admin/reservations",
  adminReservationOperations: "/admin/reservations/suivi",
  adminPayments: "/admin/paiements",
  forbidden: "/acces-refuse",
  notFound: "*",
} as const;
