import { useEffect,useMemo,useState } from "react";
import { WhistleIcon } from "@/features/refereeing/components/WhistleIcon";
import { refereeingService,type RefereeingMatch,type RefereeCandidate } from "@/features/refereeing/services/refereeingService";
import "@/features/refereeing/pages/RefereeingPage.css";
const d=(v:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"short"}).format(new Date(v+"T12:00:00")):"Date à confirmer";
export function AdminRefereeingPage(){const [items,setItems]=useState<RefereeingMatch[]>([]),[people,setPeople]=useState<RefereeCandidate[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState("");
const load=async()=>{const [a,b]=await Promise.all([refereeingService.list(),refereeingService.candidates()]);setItems(a);setPeople(b)};useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Erreur"))},[]);
const upcoming=useMemo(()=>items.filter(x=>!x.play_date||x.play_date>=new Date().toISOString().slice(0,10)),[items]),missing=upcoming.filter(x=>!x.referee_profile_id).length;
const setRef=async(x:RefereeingMatch,id:string)=>{setBusy(x.match_id);try{await refereeingService.assign(x,id||null);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setBusy("")}};
return <section className="admin-page ref-page"><header className="admin-page__header"><div><p className="admin-page__eyebrow">Championnats & tournois</p><h1><WhistleIcon aria-hidden="true" width="28" height="28" /> Gestion des arbitrages</h1><p className="admin-page__lead">Affectez les arbitres aux parties à domicile. Les membres peuvent également prendre eux-mêmes une partie libre.</p></div></header>{error&&<p className="ref-page__error" role="alert">{error}</p>}<div className="ref-page__summary"><strong>{upcoming.length}</strong><span>partie(s) à venir</span><strong>{upcoming.length-missing}</strong><span>couverte(s)</span><strong>{missing}</strong><span>arbitre(s) manquant(s)</span></div><div className="ref-grid">{upcoming.map(x=><article key={x.match_id} className={"ref-card "+(x.referee_profile_id?"ref-card--ok":"ref-card--open")}><div className="ref-card__top"><span>{x.source_type==="championship"?"Championnat":"Tournoi"}</span><strong>{x.referee_profile_id?"🟢 Couvert":"🔴 À pourvoir"}</strong></div><h3>{x.team1_label} <span>contre</span> {x.team2_label}</h3><p><strong>{d(x.play_date)} · {x.play_time?.slice(0,5).replace(":","h")??"horaire à confirmer"}</strong>{x.venue?" · "+x.venue:""}</p><label><span>Arbitre</span><select value={x.referee_profile_id??""} disabled={busy===x.match_id} onChange={e=>void setRef(x,e.target.value)}><option value="">— Aucun arbitre —</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.count} arbitrage(s)</option>)}</select></label></article>)}</div></section>}