import { useEffect,useMemo,useState } from "react";
import { WhistleIcon } from "@/features/refereeing/components/WhistleIcon";
import { refereeingService,type RefereeingMatch,type RefereeCandidate } from "@/features/refereeing/services/refereeingService";
import "@/features/refereeing/pages/RefereeingPage.css";
const d=(v:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"long"}).format(new Date(v+"T12:00:00")):"Date à confirmer";
const t=(v:string|null)=>v?v.slice(0,5).replace(":","h"):"Horaire à confirmer";
export function AdminRefereeingPage(){const [items,setItems]=useState<RefereeingMatch[]>([]),[people,setPeople]=useState<RefereeCandidate[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[groupsOpen,setGroupsOpen]=useState({championship:false,tournament:false}),[alerting,setAlerting]=useState(false);
const load=async()=>{const [a,b]=await Promise.all([refereeingService.list(),refereeingService.candidates()]);setItems(a);setPeople(b)};useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Erreur"))},[]);
const upcoming=useMemo(()=>items.filter(x=>!x.play_date||x.play_date>=new Date().toISOString().slice(0,10)),[items]),missing=upcoming.filter(x=>!x.referee_profile_id).length,championship=upcoming.filter(x=>x.source_type==="championship"),tournaments=upcoming.filter(x=>x.source_type==="tournament");
const setRef=async(x:RefereeingMatch,id:string)=>{setBusy(x.match_id);setError("");setMessage("");try{await refereeingService.assign(x,id||null);await load()}catch(e){setError(e instanceof Error?e.message:"Erreur")}finally{setBusy("")}};
const alert=async()=>{if(!missing)return;if(!window.confirm(`Envoyer une notification générale aux licenciés pour les ${missing} partie(s) encore sans arbitre ?`))return;setAlerting(true);setError("");setMessage("");try{await refereeingService.alertMembers(missing);setMessage("Notification envoyée aux licenciés.")}catch(e){setError(e instanceof Error?e.message:"Envoi impossible.")}finally{setAlerting(false)}};
const Card=({x}:{x:RefereeingMatch})=><article className={"ref-card "+(x.referee_profile_id?"ref-card--ok":"ref-card--open")}><div className="ref-card__top"><span>{x.source_type==="championship"?"Championnat":"Tournoi"}</span><strong>{x.referee_profile_id?"🟢 Couvert":"🔴 À pourvoir"}</strong></div><h3>{x.team1_label} <span>contre</span> {x.team2_label}</h3><p><strong>{d(x.play_date)} · {t(x.play_time)}</strong>{x.venue?<> · {x.venue}</>:null}</p><small>{x.competition_label}</small><label><span>Arbitre</span><select value={x.referee_profile_id??""} disabled={busy===x.match_id} onChange={e=>void setRef(x,e.target.value)}><option value="">— Aucun arbitre —</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.count} arbitrage(s)</option>)}</select></label>{x.referee_profile_id&&<button className="ref-card__withdraw" disabled={busy===x.match_id} onClick={()=>void setRef(x,"")}>{busy===x.match_id?"Retrait…":"Retirer l’arbitre"}</button>}</article>;
return <section className="admin-page ref-page"><header className="admin-page__header"><div><p className="admin-page__eyebrow">Vie du club</p><h1><WhistleIcon aria-hidden="true" width="28" height="28" /> Arbitrage</h1><p className="admin-page__lead">Suivez les parties à arbitrer et affectez, remplacez ou retirez les arbitres.</p></div><button type="button" disabled={!missing||alerting} onClick={()=>void alert()}>{alerting?"Envoi…":"🔔 Alerter les licenciés"}</button>{missing>0&&<span className="ref-alert-count">{missing} parties sans arbitre</span>}</header>{error&&<p className="ref-page__error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<div className="ref-page__summary"><strong>{upcoming.length}</strong><span>partie(s) à venir</span><strong>{upcoming.length-missing}</strong><span>couverte(s)</span><strong>{missing}</strong><span>à pourvoir</span></div>{([{key:"championship",title:"Championnat",items:championship},{key:"tournament",title:"Tournois",items:tournaments}] as const).map(group=>{const covered=group.items.filter(x=>x.referee_profile_id).length,open=group.items.length-covered;return <section className="ref-group" key={group.key}><div className="ref-group__heading"><h2>{group.title}</h2><div className="ref-group__actions"><span>{covered} couvert{covered>1?"es":""} · {open} à pourvoir</span><button type="button" onClick={()=>setGroupsOpen(v=>({...v,[group.key]:!v[group.key]}))}>{groupsOpen[group.key]?"Masquer ▲":"Afficher ▼"}</button></div></div>{groupsOpen[group.key]&&<div className="ref-grid">{group.items.length?group.items.map(x=><Card key={x.match_id} x={x}/>):<p className="ref-empty">Aucune partie à venir.</p>}</div>}</section>})}</section>}