import { useEffect,useMemo,useState } from "react";
import { UserSpaceShell } from "@/features/user-space/components/UserSpaceShell";
import { refereeingService,type RefereeingMatch } from "@/features/refereeing/services/refereeingService";
import "./RefereeingPage.css";
const date=(v:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"long"}).format(new Date(v+"T12:00:00")):"Date à confirmer";
const time=(v:string|null)=>v?v.slice(0,5).replace(":","h"):"Horaire à confirmer";
export function RefereeingPage(){const [items,setItems]=useState<RefereeingMatch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
const load=async()=>{setItems(await refereeingService.list())};useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Erreur")).finally(()=>setLoading(false))},[]);
const upcoming=useMemo(()=>items.filter(x=>!x.play_date||x.play_date>=new Date().toISOString().slice(0,10)),[items]);const mine=upcoming.filter(x=>x.is_mine),open=upcoming.filter(x=>!x.referee_profile_id);
const take=async(x:RefereeingMatch)=>{setBusy(x.match_id);setError("");try{await refereeingService.volunteer(x);await load()}catch(e){setError(e instanceof Error?e.message:"Impossible de prendre cet arbitrage.")}finally{setBusy("")}};
const Card=({x,action}:{x:RefereeingMatch;action:boolean})=><article className={"ref-card "+(x.referee_profile_id?"ref-card--ok":"ref-card--open")}><div className="ref-card__top"><span>{x.source_type==="championship"?"Championnat":"Tournoi"}</span><strong>{x.referee_profile_id?"🟢 Arbitre confirmé":"🔴 Arbitre recherché"}</strong></div><h3>{x.team1_label} <span>contre</span> {x.team2_label}</h3><p><strong>{date(x.play_date)} · {time(x.play_time)}</strong>{x.venue?<> · {x.venue}</>:null}</p><small>{x.competition_label}</small>{x.referee_name&&<p className="ref-card__ref">Arbitre : <strong>{x.referee_name}</strong></p>}{action&&<button disabled={busy===x.match_id} onClick={()=>void take(x)}>{busy===x.match_id?"Attribution…":"Je peux arbitrer"}</button>}</article>;
return <UserSpaceShell><section className="ref-page"><header><p className="ref-page__eyebrow">Vie du club</p><h1>Arbitrage</h1><p>Les parties de championnat à domicile qui ont besoin d’un arbitre.</p></header>{error&&<p role="alert" className="ref-page__error">{error}</p>}{loading?<p>Chargement…</p>:<><div className="ref-page__summary"><strong>{mine.length}</strong><span>arbitrage(s) à venir pour moi</span><strong>{open.length}</strong><span>partie(s) encore à pourvoir</span></div><h2>Mes prochains arbitrages</h2><div className="ref-grid">{mine.length?mine.map(x=><Card key={x.match_id} x={x} action={false}/>):<p className="ref-empty">Aucun arbitrage prévu.</p>}</div><h2>Parties à arbitrer</h2><div className="ref-grid">{open.length?open.map(x=><Card key={x.match_id} x={x} action/>):<p className="ref-empty">Toutes les parties sont couvertes 👍</p>}</div></>}</section></UserSpaceShell>}