import { useEffect,useMemo,useState } from "react";
import { WhistleIcon } from "@/features/refereeing/components/WhistleIcon";
import { UserSpaceShell } from "@/features/user-space/components/UserSpaceShell";
import { refereeingService,type RefereeingMatch,type RefereeingParticipation } from "@/features/refereeing/services/refereeingService";
import "./RefereeingPage.css";
const date=(v:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{weekday:"short",day:"numeric",month:"long"}).format(new Date(v+"T12:00:00")):"Date à confirmer";
const time=(v:string|null)=>v?v.slice(0,5).replace(":","h"):"Horaire à confirmer";
export function RefereeingPage(){const [items,setItems]=useState<RefereeingMatch[]>([]),[participation,setParticipation]=useState<RefereeingParticipation[]>([]),[statsOpen,setStatsOpen]=useState(false),[groupsOpen,setGroupsOpen]=useState({championship:false,tournament:false}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
const load=async()=>{const [matches,stats]=await Promise.all([refereeingService.list(),refereeingService.participation()]);setItems(matches);setParticipation(stats)};
useEffect(()=>{
 let active=true;
 const refresh=()=>load().catch(e=>{if(active)setError(e instanceof Error?e.message:"Erreur")});
 refresh().finally(()=>{if(active)setLoading(false)});
 const intervalId=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh()},60000);
 const onVisibilityChange=()=>{if(document.visibilityState==="visible")void refresh()};
 window.addEventListener("focus",onVisibilityChange);
 document.addEventListener("visibilitychange",onVisibilityChange);
 return()=>{active=false;window.clearInterval(intervalId);window.removeEventListener("focus",onVisibilityChange);document.removeEventListener("visibilitychange",onVisibilityChange)};
},[]);
const upcoming=useMemo(()=>items.filter(x=>x.is_mine||!x.play_date||x.play_date>=new Date().toISOString().slice(0,10)),[items]);const championship=upcoming.filter(x=>x.source_type==="championship"),tournaments=upcoming.filter(x=>x.source_type==="tournament");const mine=upcoming.filter(x=>x.is_mine),open=upcoming.filter(x=>!x.referee_profile_id);
const take=async(x:RefereeingMatch)=>{setBusy(x.match_id);setError("");try{await refereeingService.volunteer(x);await load()}catch(e){setError(e instanceof Error?e.message:"Impossible de prendre cet arbitrage.")}finally{setBusy("")}};
const withdraw=async(x:RefereeingMatch)=>{if(!window.confirm("Tu veux vraiment te retirer de cet arbitrage ?"))return;setBusy(x.match_id);setError("");try{await refereeingService.withdraw(x);await load()}catch(e){setError(e instanceof Error?e.message:"Impossible de retirer cet arbitrage.")}finally{setBusy("")}};
const submitScore=async(x:RefereeingMatch)=>{const a=window.prompt("Score équipe 1 (points)");if(a===null)return;const b=window.prompt("Score équipe 2 (points)");if(b===null)return;const sa=Number(a),sb=Number(b);if(!a.trim()||!b.trim()||!Number.isInteger(sa)||!Number.isInteger(sb)||sa<0||sb<0||sa===sb){setError("Saisis deux scores entiers différents.");return;}if(!window.confirm(`Confirmer le score : ${sa} – ${sb} ?`))return;setBusy(x.match_id);setError("");try{await refereeingService.submitChampionshipScore(x.match_id,sa,sb);window.alert("Résultat transmis pour validation.");await load()}catch(e){setError(e instanceof Error?e.message:"Impossible de saisir le résultat.")}finally{setBusy("")}};
const isFinished=(x:RefereeingMatch)=>{if(!x.play_date||!x.play_time)return false;const start=new Date(`${x.play_date}T${x.play_time.slice(0,5)}:00`);return !Number.isNaN(start.getTime())&&Date.now()>=start.getTime()+60*60*1000};
const totalLicensed=participation[0]?.total_licensed??0,differentReferees=participation[0]?.different_referees??0,totalAssignments=participation.reduce((sum,x)=>sum+Number(x.arbitration_count),0),participationRate=totalLicensed?Math.round(differentReferees/totalLicensed*100):0;
const Stats=()=> <section className="ref-stats"><button className="ref-stats__toggle" type="button" onClick={()=>setStatsOpen(v=>!v)} aria-expanded={statsOpen}><span><strong>Participation à l’arbitrage</strong><small>{differentReferees} arbitre(s) différent(s) / {totalLicensed} licencié(s) · {totalAssignments} arbitrage(s) attribué(s) · {participationRate}% de participation</small></span><span>{statsOpen?"Masquer le détail ▲":"Voir le détail ▼"}</span></button>{statsOpen&&<div className="ref-stats__detail"><table><thead><tr><th>Joueur</th><th>Arbitrages</th></tr></thead><tbody>{participation.map(x=><tr key={x.member_id} className={Number(x.arbitration_count)===0?"ref-stats__zero":""}><td>{x.player_name}</td><td>{x.arbitration_count}</td></tr>)}</tbody></table></div>}</section>;
const Card=({x,action}:{x:RefereeingMatch;action:boolean})=><article className={"ref-card "+(x.referee_profile_id?"ref-card--ok":"ref-card--open")}><div className="ref-card__top"><span>{x.source_type==="championship"?"Championnat":"Tournoi"}</span><strong>{x.referee_profile_id?"🟢 Arbitre confirmé":"🔴 Arbitre recherché"}</strong></div><h3>{x.team1_label} <span>contre</span> {x.team2_label}</h3><p><strong>{date(x.play_date)} · {time(x.play_time)}</strong>{x.venue?<> · {x.venue}</>:null}</p><small>{x.competition_label}</small>{x.referee_name&&<p className="ref-card__ref">Arbitre : <strong>{x.referee_name}</strong></p>}{x.is_mine&&x.source_type==="championship"&&<button disabled={busy===x.match_id||!isFinished(x)} onClick={()=>void submitScore(x)}>{isFinished(x)?"Saisir le résultat":"Résultat disponible après la partie"}</button>}{x.is_mine&&<button className="ref-card__withdraw" disabled={busy===x.match_id} onClick={()=>void withdraw(x)}>{busy===x.match_id?"Retrait…":"Me retirer"}</button>}{action&&<button disabled={busy===x.match_id} onClick={()=>void take(x)}>{busy===x.match_id?"Attribution…":"Je peux arbitrer"}</button>}</article>;
return <UserSpaceShell><section className="ref-page"><header><p className="ref-page__eyebrow">Vie du club</p><h1><WhistleIcon aria-hidden="true" width="28" height="28" /> Arbitrage</h1><p>Les parties de championnat à domicile et les tournois pour lesquels l’arbitrage est activé.</p></header>{error&&<p role="alert" className="ref-page__error">{error}</p>}{loading?<p>Chargement…</p>:<><Stats/><div className="ref-page__summary"><strong>{mine.length}</strong><span>arbitrage(s) à venir pour moi</span><strong>{open.length}</strong><span>partie(s) encore à pourvoir</span></div>{([{key:"championship",title:"Championnat",items:championship},{key:"tournament",title:"Tournois",items:tournaments}] as const).map(group=>{const groupMine=group.items.filter(x=>x.is_mine),groupOpen=group.items.filter(x=>!x.referee_profile_id);return <section className="ref-group" key={group.key}><div className="ref-group__heading"><h2>{group.title}</h2><div className="ref-group__actions"><span>{groupOpen.length} à pourvoir</span><button type="button" onClick={()=>setGroupsOpen(v=>({...v,[group.key]:!v[group.key]}))} aria-expanded={groupsOpen[group.key]}>{groupsOpen[group.key]?"Masquer ▲":"Afficher ▼"}</button></div></div>{groupsOpen[group.key]&&<><h3 className="ref-section-title">Mes prochains arbitrages</h3><div className="ref-grid">{groupMine.length?groupMine.map(x=><Card key={x.match_id} x={x} action={false}/>):<p className="ref-empty">Aucun arbitrage prévu.</p>}</div><h3 className="ref-section-title">Parties à arbitrer</h3><div className="ref-grid">{groupOpen.length?groupOpen.map(x=><Card key={x.match_id} x={x} action/>):<p className="ref-empty">Toutes les parties sont couvertes 👍</p>}</div></>}</section>})}</>}</section></UserSpaceShell>}