-- PR38: stable global member identity, seasonal licences, audited and atomic administration/imports.
create extension if not exists unaccent with schema extensions;

create function public.normalize_member_licence(value text) returns text
language sql immutable strict set search_path = '' as $$ select upper(regexp_replace(btrim(value), '\s+', '', 'g')) $$;
create function public.normalize_member_identity(value text) returns text
language sql immutable strict set search_path = '' as $$ select upper(regexp_replace(extensions.unaccent(value), '[[:space:]''’\-]+', '', 'g')) $$;
create function public.member_category(birth_date date, season_ends_on date) returns text
language sql immutable strict set search_path = '' as $$
 select case when extract(year from season_ends_on)-extract(year from birth_date)<=9 then 'M10'
 when extract(year from season_ends_on)-extract(year from birth_date)<=11 then 'M12'
 when extract(year from season_ends_on)-extract(year from birth_date)<=13 then 'M14'
 when extract(year from season_ends_on)-extract(year from birth_date)<=15 then 'M16'
 when extract(year from season_ends_on)-extract(year from birth_date)<=18 then 'M19'
 when extract(year from season_ends_on)-extract(year from birth_date)<=21 then 'M22'
 when extract(year from season_ends_on)-extract(year from birth_date)<=44 then 'Senior'
 when extract(year from season_ends_on)-extract(year from birth_date)<=54 then 'Vétéran A/B' else 'Vétéran Senior' end $$;

alter table public.club_members add column licence_number_normalized text;
alter table public.club_members add column last_name_normalized text;
alter table public.club_members add column first_name_normalized text;
update public.club_members set licence_number=btrim(licence_number), licence_number_normalized=public.normalize_member_licence(licence_number), last_name_normalized=public.normalize_member_identity(last_name), first_name_normalized=public.normalize_member_identity(first_name);
do $$ begin
 if exists(select 1 from public.club_members where birth_date is null or gender is null or gender not in ('male','female')) then raise exception 'PR38 migration: complete birth_date and gender before applying'; end if;
 if exists(select 1 from public.club_members group by licence_number_normalized having count(*)>1) then raise exception 'PR38 migration: duplicate normalized licence'; end if;
end $$;
alter table public.club_members alter column birth_date set not null;
alter table public.club_members alter column gender set not null;
alter table public.club_members alter column licence_number_normalized set not null;
alter table public.club_members alter column last_name_normalized set not null;
alter table public.club_members alter column first_name_normalized set not null;
alter table public.club_members add constraint club_members_gender_check check(gender in ('male','female'));
alter table public.club_members add constraint club_members_birth_not_future check(birth_date<=current_date);
alter table public.club_members drop constraint if exists club_members_licence_number_key;
create unique index club_members_licence_normalized_unique on public.club_members(licence_number_normalized);
create index club_members_identity_search on public.club_members(last_name_normalized,first_name_normalized,birth_date);

create function public.sync_member_normalization() returns trigger language plpgsql set search_path='' as $$ begin
 new.licence_number=btrim(new.licence_number);new.licence_number_normalized=public.normalize_member_licence(new.licence_number);new.last_name=btrim(new.last_name);new.first_name=btrim(new.first_name);new.last_name_normalized=public.normalize_member_identity(new.last_name);new.first_name_normalized=public.normalize_member_identity(new.first_name);new.updated_at=now();return new;end $$;
create trigger sync_member_normalization before insert or update of licence_number,last_name,first_name on public.club_members for each row execute function public.sync_member_normalization();

create table public.club_member_seasons(id uuid primary key default gen_random_uuid(),club_member_id uuid not null references public.club_members(id) on delete restrict,club_id uuid not null references public.clubs(id) on delete restrict,club_season_id uuid not null references public.club_seasons(id) on delete restrict,ranking text,category text not null,is_licensed boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),unique(club_member_id,club_season_id));
create unique index club_seasons_id_club_unique on public.club_seasons(id,club_id);
alter table public.club_member_seasons add constraint club_member_season_same_club foreign key(club_season_id,club_id) references public.club_seasons(id,club_id);

-- Create missing conventional historical seasons, then backfill without discarding a member.
insert into public.club_seasons(club_id,name,starts_on,ends_on,is_active)
select distinct m.club_id,replace(m.season,'/','-'),make_date(substring(m.season from '([0-9]{4})')::int,7,1),make_date(substring(m.season from '[0-9]{4}[-/]([0-9]{4})')::int,6,30),false from public.club_members m
where m.season~'^[0-9]{4}[-/][0-9]{4}$' on conflict(club_id,name) do nothing;
insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category)
select m.id,m.club_id,s.id,m.ranking,coalesce(nullif(m.category,''),public.member_category(m.birth_date,s.ends_on)) from public.club_members m join public.club_seasons s on s.club_id=m.club_id and (s.name=m.season or s.name=replace(m.season,'/','-')) on conflict do nothing;
do $$ begin if exists(select 1 from public.club_members m where not exists(select 1 from public.club_member_seasons ms where ms.club_member_id=m.id)) then raise exception 'PR38 migration: historical season could not be deterministically migrated';end if;end $$;
alter table public.club_members drop column ranking,drop column category,drop column season;

create function public.sync_member_season_category() returns trigger language plpgsql security definer set search_path='' as $$ declare dob date;ending date;begin select m.birth_date,s.ends_on into dob,ending from public.club_members m join public.club_seasons s on s.id=new.club_season_id where m.id=new.club_member_id;new.category=public.member_category(dob,ending);new.updated_at=now();new.updated_by=coalesce(auth.uid(),new.updated_by);return new;end $$;
create trigger sync_member_season_category before insert or update on public.club_member_seasons for each row execute function public.sync_member_season_category();

create type public.club_member_import_status as enum('draft','validated','processing','completed','failed','cancelled');
create table public.club_member_imports(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id),club_season_id uuid not null references public.club_seasons(id),file_name text not null,file_size integer not null check(file_size between 0 and 5242880),file_hash text not null,encoding text not null check(encoding in ('utf-8','windows-1252')),separator text not null check(separator in (',',';',E'\t')),column_mapping jsonb not null default '{}',options jsonb not null default '{}',status public.club_member_import_status not null default 'draft',author_id uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),validated_at timestamptz,executed_at timestamptz,created_count integer not null default 0,updated_count integer not null default 0,reactivated_count integer not null default 0,unchanged_count integer not null default 0,ignored_count integer not null default 0,error_count integer not null default 0,warning_count integer not null default 0,global_error text);
create table public.club_member_import_rows(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.club_member_imports(id) on delete cascade,line_number integer not null,original_data jsonb not null,normalized_data jsonb not null,planned_action text not null,admin_decision jsonb not null default '{}',errors jsonb not null default '[]',warnings jsonb not null default '[]',detected_member_id uuid references public.club_members(id),observed_updated_at timestamptz,executed_action text,before_values jsonb,after_values jsonb,unique(import_id,line_number));
create table public.club_member_audit_log(id uuid primary key default gen_random_uuid(),club_member_id uuid references public.club_members(id) on delete restrict,club_id uuid not null references public.clubs(id),club_season_id uuid references public.club_seasons(id),author_id uuid references public.profiles(id),occurred_at timestamptz not null default now(),action text not null,before_values jsonb,after_values jsonb,import_id uuid references public.club_member_imports(id),reason text,metadata jsonb not null default '{}');
create table public.club_member_access_log(id uuid primary key default gen_random_uuid(),club_member_id uuid not null references public.club_members(id),requesting_club_id uuid not null references public.clubs(id),member_club_id uuid not null references public.clubs(id),accessed_by uuid not null references public.profiles(id),accessed_at timestamptz not null default now());

alter table public.club_member_seasons enable row level security;alter table public.club_member_imports enable row level security;alter table public.club_member_import_rows enable row level security;alter table public.club_member_audit_log enable row level security;alter table public.club_member_access_log enable row level security;
drop policy if exists club_members_admin_all on public.club_members;
create policy club_members_manager_read on public.club_members for select to authenticated using(public.has_club_permission(club_id,'members.manage') or exists(select 1 from public.profiles p where p.id=auth.uid() and p.member_id=club_members.id));
create policy member_seasons_read on public.club_member_seasons for select to authenticated using(public.has_club_permission(club_id,'members.manage') or exists(select 1 from public.profiles p where p.id=auth.uid() and p.member_id=club_member_seasons.club_member_id));
create policy member_imports_manager_read on public.club_member_imports for select to authenticated using(public.has_club_permission(club_id,'members.manage'));
create policy member_import_rows_manager_read on public.club_member_import_rows for select to authenticated using(exists(select 1 from public.club_member_imports i where i.id=import_id and public.has_club_permission(i.club_id,'members.manage')));
create policy member_audit_manager_read on public.club_member_audit_log for select to authenticated using(public.has_club_permission(club_id,'members.manage'));
create policy member_access_own_read on public.club_member_access_log for select to authenticated using(accessed_by=auth.uid());
create function public.admin_list_club_members(filters jsonb default '{}') returns table(id uuid,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz)
language sql stable security definer set search_path='' as $$ with context as(select public.admin_current_club_id() club_id),active_season as(select s.id from public.club_seasons s,context c where s.club_id=c.club_id and s.is_active),q as(select coalesce(filters->>'search','') value)
select m.id,m.licence_number,m.last_name,m.first_name,m.birth_date,m.gender,m.email,m.phone,m.is_active,ms.ranking,ms.category,coalesce(ms.is_licensed,false),exists(select 1 from public.profiles p where p.member_id=m.id),m.updated_at from public.club_members m join context c on c.club_id=m.club_id left join active_season a on true left join public.club_member_seasons ms on ms.club_member_id=m.id and ms.club_season_id=a.id,q where public.has_club_permission(c.club_id,'members.manage') and (q.value='' or m.licence_number_normalized like '%'||public.normalize_member_licence(q.value)||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(q.value)||'%' or m.first_name_normalized like '%'||public.normalize_member_identity(q.value)||'%') and (coalesce(filters->>'active','all')='all' or m.is_active=(filters->>'active')::boolean) and (coalesce(filters->>'licensed','all')='all' or coalesce(ms.is_licensed,false)=(filters->>'licensed')::boolean) order by m.last_name_normalized,m.first_name_normalized limit least(coalesce((filters->>'page_size')::int,50),100) offset (greatest(coalesce((filters->>'page')::int,1),1)-1)*least(coalesce((filters->>'page_size')::int,50),100) $$;

create function public.admin_create_member(payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$ declare club uuid:=public.admin_current_club_id();season public.club_seasons%rowtype;result uuid;begin
 if not public.has_club_permission(club,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select * into season from public.club_seasons s where s.club_id=club and s.is_active for share;if season.id is null then raise exception 'Aucune saison active' using errcode='22023';end if;
 if exists(select 1 from public.club_members m where m.last_name_normalized=public.normalize_member_identity(payload->>'lastName') and m.first_name_normalized=public.normalize_member_identity(payload->>'firstName') and m.birth_date=(payload->>'birthDate')::date) then raise exception 'Une identité similaire existe déjà' using errcode='23505';end if;
 insert into public.club_members(club_id,licence_number,last_name,first_name,birth_date,gender,email,phone,is_active) values(club,payload->>'licenceNumber',payload->>'lastName',payload->>'firstName',(payload->>'birthDate')::date,payload->>'gender',nullif(payload->>'email',''),nullif(payload->>'phone',''),true) returning id into result;
 insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,created_by,updated_by) values(result,club,season.id,nullif(payload->>'ranking',''),public.member_category((payload->>'birthDate')::date,season.ends_on),auth.uid(),auth.uid());insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,after_values) values(result,club,season.id,auth.uid(),'manual_created',payload);return result;end $$;

create function public.admin_set_member_active(target_member_id uuid,target_active boolean,expected_updated_at timestamptz,reason text) returns void language plpgsql security definer set search_path='' as $$ declare old public.club_members%rowtype;begin select * into old from public.club_members where id=target_member_id for update;if old.id is null or not public.has_club_permission(old.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;if old.updated_at<>expected_updated_at then raise exception 'La fiche a changé' using errcode='40001';end if;if btrim(coalesce(reason,''))='' then raise exception 'Motif obligatoire' using errcode='22023';end if;update public.club_members set is_active=target_active,updated_at=now() where id=old.id;insert into public.club_member_audit_log(club_member_id,club_id,author_id,action,before_values,after_values,reason) select old.id,old.club_id,auth.uid(),case when target_active then 'manual_reactivated' else 'manual_deactivated' end,to_jsonb(old),to_jsonb(current_member),reason from public.club_members current_member where current_member.id=old.id;end $$;

create function public.admin_search_members_global(filters jsonb default '{}') returns table(id uuid,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz) language plpgsql stable security definer set search_path='' as $$ declare requester uuid:=public.admin_current_club_id();begin if not(public.has_club_permission(requester,'members.manage') or public.has_club_permission(requester,'tournaments.manage')) then raise exception 'Forbidden' using errcode='42501';end if;return query select m.id,m.licence_number,m.last_name,m.first_name,m.birth_date,m.gender,m.email,m.phone,m.is_active,ms.ranking,ms.category,coalesce(ms.is_licensed,false),exists(select 1 from public.profiles p where p.member_id=m.id),m.updated_at from public.club_members m left join public.club_member_seasons ms on ms.club_member_id=m.id and (filters->>'season_id' is null or ms.club_season_id=(filters->>'season_id')::uuid) where coalesce(filters->>'search','')='' or m.licence_number_normalized like '%'||public.normalize_member_licence(filters->>'search')||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%' order by m.last_name_normalized limit least(coalesce((filters->>'page_size')::int,50),100);end $$;

create function public.admin_create_member_import(payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$ declare club uuid:=public.admin_current_club_id();season uuid;result uuid;begin if not public.has_club_permission(club,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select id into season from public.club_seasons where club_id=club and is_active;if season is null then raise exception 'Aucune saison active' using errcode='22023';end if;insert into public.club_member_imports(club_id,club_season_id,file_name,file_size,file_hash,encoding,separator,column_mapping,options) values(club,season,payload->>'file_name',(payload->>'file_size')::int,payload->>'file_hash',payload->>'encoding',payload->>'separator',coalesce(payload->'mapping','{}'),coalesce(payload->'options','{}')) returning id into result;return result;end $$;
create function public.admin_validate_member_import(target_import_id uuid,rows jsonb) returns void language plpgsql security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;begin select * into target from public.club_member_imports where id=target_import_id for update;if target.status<>'draft' or not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Import non modifiable' using errcode='42501';end if;if jsonb_array_length(rows)>10000 then raise exception 'Trop de lignes' using errcode='22023';end if;insert into public.club_member_import_rows(import_id,line_number,original_data,normalized_data,planned_action,admin_decision,errors,warnings,detected_member_id,observed_updated_at) select target.id,(r->>'lineNumber')::int,coalesce(r->'original','{}'),r->'data',r->>'action',coalesce(r->'decision','{}'),coalesce(r->'errors','[]'),coalesce(r->'warnings','[]'),nullif(r->>'memberId','')::uuid,nullif(r->>'observedUpdatedAt','')::timestamptz from jsonb_array_elements(rows) r;update public.club_member_imports set status='validated',validated_at=now(),error_count=(select count(*) from public.club_member_import_rows where import_id=target.id and jsonb_array_length(errors)>0),warning_count=(select count(*) from public.club_member_import_rows where import_id=target.id and jsonb_array_length(warnings)>0) where id=target.id;end $$;
create function public.admin_execute_member_import(target_import_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;r public.club_member_import_rows%rowtype;m public.club_members%rowtype;season public.club_seasons%rowtype;created_n int:=0;updated_n int:=0;reactivated_n int:=0;ignored_n int:=0;processing_started boolean:=false;begin
 select * into target from public.club_member_imports where id=target_import_id for update;if target.status<>'validated' then raise exception 'Import déjà exécuté ou non validé' using errcode='55000';end if;if not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select * into season from public.club_seasons where id=target.club_season_id and club_id=target.club_id and is_active for share;if season.id is null then raise exception 'La saison ciblée n’est plus active' using errcode='40001';end if;if exists(select 1 from public.club_member_import_rows where import_id=target.id and executed_action is null and jsonb_array_length(errors)>0 and not coalesce((admin_decision->>'ignored')::boolean,false)) then raise exception 'Des erreurs bloquantes restent à résoudre' using errcode='22023';end if;if exists(select 1 from public.club_member_import_rows where import_id=target.id and not coalesce((admin_decision->>'ignored')::boolean,false) group by normalized_data->>'licenceNumber' having count(*)>1) then raise exception 'Doublons de licence dans le fichier' using errcode='23505';end if;update public.club_member_imports set status='processing' where id=target.id;
 for r in select * from public.club_member_import_rows where import_id=target.id order by line_number loop
  if coalesce((r.admin_decision->>'ignored')::boolean,false) then update public.club_member_import_rows set executed_action='ignored' where id=r.id;ignored_n:=ignored_n+1;continue;end if;
  select * into m from public.club_members where licence_number_normalized=public.normalize_member_licence(r.normalized_data->>'licenceNumber') for update;
  if m.id is not null and m.club_id<>target.club_id then raise exception 'Licence appartenant à un autre club (ligne %)',r.line_number using errcode='42501';end if;
  if m.id is not null and r.observed_updated_at is not null and m.updated_at<>r.observed_updated_at then raise exception 'Conflit de concurrence ligne %',r.line_number using errcode='40001';end if;
  if m.id is null then insert into public.club_members(club_id,licence_number,last_name,first_name,birth_date,gender,email,phone) values(target.club_id,r.normalized_data->>'licenceNumber',r.normalized_data->>'lastName',r.normalized_data->>'firstName',(r.normalized_data->>'birthDate')::date,r.normalized_data->>'gender',nullif(r.normalized_data->>'email',''),nullif(r.normalized_data->>'phone','')) returning * into m;created_n:=created_n+1;
  else update public.club_members set last_name=coalesce(nullif(r.normalized_data->>'lastName',''),last_name),first_name=coalesce(nullif(r.normalized_data->>'firstName',''),first_name),birth_date=coalesce(nullif(r.normalized_data->>'birthDate','')::date,birth_date),gender=coalesce(nullif(r.normalized_data->>'gender',''),gender),email=coalesce(nullif(r.normalized_data->>'email',''),email),phone=coalesce(nullif(r.normalized_data->>'phone',''),phone),is_active=case when coalesce((r.admin_decision->>'reactivate')::boolean,false) then true else is_active end where id=m.id returning * into m;updated_n:=updated_n+1;if not m.is_active and coalesce((r.admin_decision->>'reactivate')::boolean,false) then reactivated_n:=reactivated_n+1;end if;end if;
  insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,created_by,updated_by) values(m.id,target.club_id,season.id,nullif(r.normalized_data->>'ranking',''),public.member_category(m.birth_date,season.ends_on),auth.uid(),auth.uid()) on conflict(club_member_id,club_season_id) do update set ranking=coalesce(nullif(excluded.ranking,''),club_member_seasons.ranking),is_licensed=true,updated_at=now(),updated_by=auth.uid();
  insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,after_values,import_id,metadata) values(m.id,target.club_id,season.id,auth.uid(),case when r.planned_action='create' then 'import_created' else 'import_updated' end,to_jsonb(m),target.id,jsonb_build_object('line',r.line_number,'decision',r.admin_decision));update public.club_member_import_rows set executed_action=case when r.planned_action='create' then 'created' else 'updated' end,after_values=to_jsonb(m) where id=r.id;
 end loop;update public.club_member_imports set status='completed',executed_at=now(),created_count=created_n,updated_count=updated_n,reactivated_count=reactivated_n,ignored_count=ignored_n where id=target.id;
exception when others then if target.id is not null then update public.club_member_imports set status='failed',executed_at=now(),global_error=sqlerrm where id=target.id;end if;end $$;

create or replace function public.is_active_licensee(target_profile_id uuid,target_date date default current_date) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles p left join public.club_members m on m.id=p.member_id where p.id=target_profile_id and ((m.is_active and exists(select 1 from public.club_seasons s join public.club_member_seasons ms on ms.club_season_id=s.id and ms.club_member_id=m.id where s.club_id=m.club_id and s.is_active and ms.is_licensed)) or (p.member_id is null and p.membership_status='active'::public.membership_status and p.membership_validated_at is not null and p.membership_validated_by is not null and (p.membership_valid_until is null or p.membership_valid_until>=target_date)))) $$;
create or replace function public.find_member_by_licence(licence_number text,last_name text,first_name text,birth_date date) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.club_members m where m.licence_number_normalized=public.normalize_member_licence(licence_number) and m.last_name_normalized=public.normalize_member_identity(last_name) and m.first_name_normalized=public.normalize_member_identity(first_name) and m.birth_date=find_member_by_licence.birth_date) $$;

revoke all on function public.normalize_member_licence(text),public.normalize_member_identity(text),public.member_category(date,date),public.admin_list_club_members(jsonb),public.admin_create_member(jsonb),public.admin_set_member_active(uuid,boolean,timestamptz,text),public.admin_search_members_global(jsonb),public.admin_create_member_import(jsonb),public.admin_validate_member_import(uuid,jsonb),public.admin_execute_member_import(uuid) from public;
grant execute on function public.admin_list_club_members(jsonb),public.admin_create_member(jsonb),public.admin_set_member_active(uuid,boolean,timestamptz,text),public.admin_search_members_global(jsonb),public.admin_create_member_import(jsonb),public.admin_validate_member_import(uuid,jsonb),public.admin_execute_member_import(uuid) to authenticated;
comment on table public.club_members is 'Stable global person identity and current club; contact email is never an Auth login address.';
comment on table public.club_member_seasons is 'Annual licence truth and immutable historical represented club.';
create function public.admin_list_member_imports() returns setof public.club_member_imports language sql stable security definer set search_path='' as $$ select i.* from public.club_member_imports i where public.has_club_permission(i.club_id,'members.manage') and i.club_id=public.admin_current_club_id() order by i.created_at desc $$;
revoke all on function public.admin_list_member_imports() from public;grant execute on function public.admin_list_member_imports() to authenticated;

create or replace function public.link_profile_to_member(licence_number text,last_name text,first_name text,birth_date date) returns uuid language plpgsql security definer set search_path='' as $$ declare profile uuid:=auth.uid();member uuid;other uuid;begin if profile is null then raise exception 'Authentication required' using errcode='42501';end if;select m.id into member from public.club_members m where m.licence_number_normalized=public.normalize_member_licence(licence_number) and m.last_name_normalized=public.normalize_member_identity(last_name) and m.first_name_normalized=public.normalize_member_identity(first_name) and m.birth_date=link_profile_to_member.birth_date for update;if member is null then raise exception 'Member identity does not match the club licence registry' using errcode='P0002';end if;select p.id into other from public.profiles p where p.member_id=member;if other is not null and other<>profile then raise exception 'Licence is already linked to another account' using errcode='23505';end if;perform set_config('app.allow_profile_member_link','on',true);update public.profiles set member_id=member,updated_at=now() where id=profile;if not found then raise exception 'Current profile not found' using errcode='P0002';end if;return member;end $$;
revoke all on function public.link_profile_to_member(text,text,text,date) from public;grant execute on function public.link_profile_to_member(text,text,text,date) to authenticated;

-- Complete administrative surface (the earlier declarations are replaced here so a failed
-- deployment never exposes an incomplete RPC contract).
drop function public.admin_list_club_members(jsonb);
create function public.admin_list_club_members(filters jsonb default '{}') returns table(id uuid,club_id uuid,club_name text,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz,total_count bigint)
language plpgsql stable security definer set search_path='' as $$ declare current_club uuid:=public.admin_current_club_id();begin
 if not public.has_club_permission(current_club,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;
 return query with active_season as(select s.id from public.club_seasons s where s.club_id=current_club and s.is_active),result as(select m.*,c.name club_name,ms.ranking,ms.category,coalesce(ms.is_licensed,false) licensed,exists(select 1 from public.profiles p where p.member_id=m.id) linked from public.club_members m join public.clubs c on c.id=m.club_id left join active_season a on true left join public.club_member_seasons ms on ms.club_member_id=m.id and ms.club_season_id=a.id where m.club_id=current_club and (coalesce(filters->>'search','')='' or m.licence_number_normalized like '%'||public.normalize_member_licence(filters->>'search')||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%' or m.first_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%') and (coalesce(filters->>'active','all')='all' or m.is_active=(filters->>'active')::boolean) and (coalesce(filters->>'licensed','all')='all' or coalesce(ms.is_licensed,false)=(filters->>'licensed')::boolean)) select r.id,r.club_id,r.club_name,r.licence_number,r.last_name,r.first_name,r.birth_date,r.gender,r.email,r.phone,r.is_active,r.ranking,r.category,r.licensed,r.linked,r.updated_at,count(*) over() from result r order by case when filters->>'sort'='licence' then r.licence_number_normalized end,case when filters->>'sort'='first_name' then r.first_name_normalized end,r.last_name_normalized,r.first_name_normalized limit least(greatest(coalesce((filters->>'page_size')::int,50),1),100) offset (greatest(coalesce((filters->>'page')::int,1),1)-1)*least(greatest(coalesce((filters->>'page_size')::int,50),1),100);end $$;

drop function public.admin_search_members_global(jsonb);
create function public.admin_search_members_global(filters jsonb default '{}') returns table(id uuid,club_id uuid,club_name text,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz,total_count bigint)
language plpgsql stable security definer set search_path='' as $$ declare requester uuid:=public.admin_current_club_id();begin
 if not(public.has_club_permission(requester,'members.manage') or public.has_club_permission(requester,'tournaments.manage')) then raise exception 'Forbidden' using errcode='42501';end if;
 return query with result as(select m.*,c.name club_name,ms.ranking,ms.category,coalesce(ms.is_licensed,false) licensed,exists(select 1 from public.profiles p where p.member_id=m.id) linked from public.club_members m join public.clubs c on c.id=m.club_id left join public.club_member_seasons ms on ms.club_member_id=m.id and (filters->>'season_id' is null or ms.club_season_id=(filters->>'season_id')::uuid) where (coalesce(filters->>'search','')='' or m.licence_number_normalized like '%'||public.normalize_member_licence(filters->>'search')||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%' or m.first_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%') and (filters->>'club_id' is null or m.club_id=(filters->>'club_id')::uuid) and (filters->>'active' is null or m.is_active=(filters->>'active')::boolean) and (filters->>'licensed' is null or coalesce(ms.is_licensed,false)=(filters->>'licensed')::boolean) and (filters->>'ranking' is null or ms.ranking=filters->>'ranking') and (filters->>'category' is null or ms.category=filters->>'category')) select r.id,r.club_id,r.club_name,r.licence_number,r.last_name,r.first_name,r.birth_date,r.gender,r.email,r.phone,r.is_active,r.ranking,r.category,r.licensed,r.linked,r.updated_at,count(*) over() from result r order by r.last_name_normalized,r.first_name_normalized limit least(greatest(coalesce((filters->>'page_size')::int,50),1),100) offset (greatest(coalesce((filters->>'page')::int,1),1)-1)*least(greatest(coalesce((filters->>'page_size')::int,50),1),100);end $$;

create function public.admin_get_member(target_member_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare requester uuid:=public.admin_current_club_id();member public.club_members%rowtype;result jsonb;begin
 if not(public.has_club_permission(requester,'members.manage') or public.has_club_permission(requester,'tournaments.manage')) then raise exception 'Forbidden' using errcode='42501';end if;select * into member from public.club_members where id=target_member_id;if member.id is null then raise exception 'Licencié introuvable' using errcode='P0002';end if;if member.club_id<>requester then insert into public.club_member_access_log(club_member_id,requesting_club_id,member_club_id,accessed_by) values(member.id,requester,member.club_id,auth.uid());end if;
 select to_jsonb(member)||jsonb_build_object('club_name',c.name,'linked_account',exists(select 1 from public.profiles p where p.member_id=member.id),'canEdit',public.has_club_permission(member.club_id,'members.manage'),'seasons',coalesce((select jsonb_agg(jsonb_build_object('id',ms.id,'clubSeasonId',s.id,'seasonName',s.name,'isActive',s.is_active,'clubId',ms.club_id,'clubName',hc.name,'ranking',ms.ranking,'category',ms.category,'isLicensed',ms.is_licensed,'updatedAt',ms.updated_at) order by s.ends_on desc) from public.club_member_seasons ms join public.club_seasons s on s.id=ms.club_season_id join public.clubs hc on hc.id=ms.club_id where ms.club_member_id=member.id),'[]')) into result from public.clubs c where c.id=member.club_id;return result;end $$;

create function public.admin_update_member(target_member_id uuid,payload jsonb,expected_updated_at timestamptz,reason text default null) returns void language plpgsql security definer set search_path='' as $$ declare old public.club_members%rowtype;changed_sensitive boolean;active_season uuid;season_before jsonb;begin
 select * into old from public.club_members where id=target_member_id for update;if old.id is null or not public.has_club_permission(old.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;if old.updated_at<>expected_updated_at then raise exception 'La fiche a changé depuis son ouverture' using errcode='40001';end if;if payload?'club_id' or payload?'licenceNumber' then raise exception 'Club et licence utilisent des commandes dédiées' using errcode='22023';end if;
 changed_sensitive=(payload?'birthDate' and (payload->>'birthDate')::date<>old.birth_date) or (payload?'gender' and payload->>'gender'<>old.gender) or ((payload?'lastName') and (payload?'firstName') and (payload?'birthDate'));if changed_sensitive and (btrim(coalesce(reason,''))='' or not coalesce((payload->>'confirmedSensitive')::boolean,false)) then raise exception 'Motif et confirmation obligatoires pour une modification sensible' using errcode='22023';end if;
 if coalesce(nullif(payload->>'lastName',''),old.last_name)='' or coalesce(nullif(payload->>'firstName',''),old.first_name)='' or coalesce(nullif(payload->>'gender',''),old.gender) not in ('male','female') or coalesce(nullif(payload->>'birthDate','')::date,old.birth_date)>current_date then raise exception 'Données métier invalides' using errcode='22023';end if;
 if exists(select 1 from public.club_members m where m.id<>old.id and m.last_name_normalized=public.normalize_member_identity(coalesce(nullif(payload->>'lastName',''),old.last_name)) and m.first_name_normalized=public.normalize_member_identity(coalesce(nullif(payload->>'firstName',''),old.first_name)) and m.birth_date=coalesce(nullif(payload->>'birthDate','')::date,old.birth_date)) then raise exception 'Une identité similaire existe déjà' using errcode='23505';end if;
 update public.club_members set last_name=coalesce(nullif(payload->>'lastName',''),last_name),first_name=coalesce(nullif(payload->>'firstName',''),first_name),birth_date=coalesce(nullif(payload->>'birthDate','')::date,birth_date),gender=coalesce(nullif(payload->>'gender',''),gender),email=case when payload?'email' then nullif(payload->>'email','') else email end,phone=case when payload?'phone' then nullif(payload->>'phone','') else phone end where id=old.id;select id into active_season from public.club_seasons where club_id=old.club_id and is_active;if payload?'ranking' then select to_jsonb(ms) into season_before from public.club_member_seasons ms where ms.club_member_id=old.id and ms.club_season_id=active_season;update public.club_member_seasons set ranking=nullif(payload->>'ranking',''),updated_at=now(),updated_by=auth.uid() where club_member_id=old.id and club_season_id=active_season;insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,reason) select old.id,old.club_id,active_season,auth.uid(),'season_updated',season_before,to_jsonb(ms),reason from public.club_member_seasons ms where ms.club_member_id=old.id and ms.club_season_id=active_season;end if;insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,reason) select old.id,old.club_id,active_season,auth.uid(),'manual_updated',to_jsonb(old),to_jsonb(m),reason from public.club_members m where m.id=old.id;end $$;
create function public.admin_correct_member_licence(target_member_id uuid,target_licence_number text,expected_updated_at timestamptz,reason text) returns void language plpgsql security definer set search_path='' as $$ declare old public.club_members%rowtype;begin select * into old from public.club_members where id=target_member_id for update;if old.id is null or not public.has_club_permission(old.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;if old.updated_at<>expected_updated_at then raise exception 'La fiche a changé' using errcode='40001';end if;if btrim(coalesce(reason,''))='' or public.normalize_member_licence(target_licence_number)='' then raise exception 'Licence et motif obligatoires' using errcode='22023';end if;if exists(select 1 from public.club_members where id<>old.id and licence_number_normalized=public.normalize_member_licence(target_licence_number)) then raise exception 'Ce numéro de licence existe déjà' using errcode='23505';end if;update public.club_members set licence_number=target_licence_number where id=old.id;insert into public.club_member_audit_log(club_member_id,club_id,author_id,action,before_values,after_values,reason) select old.id,old.club_id,auth.uid(),'licence_corrected',to_jsonb(old),to_jsonb(m),reason from public.club_members m where m.id=old.id;end $$;
create function public.admin_update_member_season(target_member_id uuid,target_season_id uuid,target_ranking text,target_is_licensed boolean,expected_updated_at timestamptz,reason text) returns void language plpgsql security definer set search_path='' as $$ declare member public.club_members%rowtype;season public.club_seasons%rowtype;old public.club_member_seasons%rowtype;begin select * into member from public.club_members where id=target_member_id for update;select * into season from public.club_seasons where id=target_season_id;if member.id is null or season.id is null or not public.has_club_permission(member.club_id,'members.manage') or season.club_id<>member.club_id then raise exception 'Forbidden' using errcode='42501';end if;select * into old from public.club_member_seasons where club_member_id=member.id and club_season_id=season.id for update;if old.id is not null and old.updated_at<>expected_updated_at then raise exception 'La saison a changé' using errcode='40001';end if;if (not season.is_active) and btrim(coalesce(reason,''))='' then raise exception 'Motif obligatoire pour une ancienne saison' using errcode='22023';end if;insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,is_licensed,created_by,updated_by) values(member.id,member.club_id,season.id,nullif(btrim(target_ranking),''),public.member_category(member.birth_date,season.ends_on),target_is_licensed,auth.uid(),auth.uid()) on conflict(club_member_id,club_season_id) do update set ranking=excluded.ranking,is_licensed=excluded.is_licensed,updated_by=auth.uid();insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,reason) select member.id,member.club_id,season.id,auth.uid(),case when old.id is null then 'season_created' when not season.is_active then 'historical_season_updated' else 'season_updated' end,to_jsonb(old),to_jsonb(ms),reason from public.club_member_seasons ms where ms.club_member_id=member.id and ms.club_season_id=season.id;end $$;

create or replace function public.admin_validate_member_import(target_import_id uuid,rows jsonb) returns void language plpgsql security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;r jsonb;normalized jsonb;member public.club_members%rowtype;errors jsonb;warnings jsonb;action text;duplicate_count int;begin select * into target from public.club_member_imports where id=target_import_id for update;if target.status<>'draft' or not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Import non modifiable' using errcode='42501';end if;if jsonb_typeof(rows)<>'array' or jsonb_array_length(rows)=0 or jsonb_array_length(rows)>10000 then raise exception 'Nombre de lignes invalide' using errcode='22023';end if;delete from public.club_member_import_rows where import_id=target.id;
 for r in select * from jsonb_array_elements(rows) loop normalized=jsonb_build_object('licenceNumber',public.normalize_member_licence(r#>>'{data,licenceNumber}'),'lastName',btrim(r#>>'{data,lastName}'),'firstName',btrim(r#>>'{data,firstName}'),'birthDate',r#>>'{data,birthDate}','gender',r#>>'{data,gender}','email',coalesce(r#>>'{data,email}',''),'phone',coalesce(r#>>'{data,phone}',''),'ranking',coalesce(r#>>'{data,ranking}',''));errors='[]';warnings='[]';action='create';
  if normalized->>'licenceNumber'='' or normalized->>'lastName'='' or normalized->>'firstName'='' or normalized->>'birthDate' is null or normalized->>'gender' not in ('male','female') then errors=errors||'"Données obligatoires invalides"'::jsonb;action='error';elsif (normalized->>'birthDate')::date>current_date then errors=errors||'"Date de naissance future"'::jsonb;action='error';end if;
  select count(*) into duplicate_count from jsonb_array_elements(rows) x where public.normalize_member_licence(x#>>'{data,licenceNumber}')=normalized->>'licenceNumber';if duplicate_count>1 then errors=errors||'"Licence dupliquée dans le fichier"'::jsonb;action='duplicate';end if;
  select * into member from public.club_members where licence_number_normalized=normalized->>'licenceNumber';if member.id is not null and member.club_id<>target.club_id then errors=errors||'"Licence appartenant à un autre club"'::jsonb;action='other_club';elsif member.id is not null then if public.normalize_member_identity(normalized->>'lastName')<>member.last_name_normalized and public.normalize_member_identity(normalized->>'firstName')<>member.first_name_normalized and (normalized->>'birthDate')::date<>member.birth_date then errors=errors||'"Conflit d’identité complet"'::jsonb;action='identity_conflict';elsif (normalized->>'birthDate')::date<>member.birth_date or normalized->>'gender'<>member.gender then warnings=warnings||'"Naissance ou sexe modifié : confirmation requise"'::jsonb;action='sensitive_warning';elsif not member.is_active then action='inactive';elsif public.normalize_member_identity(normalized->>'lastName')=member.last_name_normalized and public.normalize_member_identity(normalized->>'firstName')=member.first_name_normalized and (normalized->>'birthDate')::date=member.birth_date and normalized->>'gender'=member.gender and (normalized->>'email'='' or normalized->>'email'=coalesce(member.email,'')) and (normalized->>'phone'='' or normalized->>'phone'=coalesce(member.phone,'')) and exists(select 1 from public.club_member_seasons current_ms where current_ms.club_member_id=member.id and current_ms.club_season_id=target.club_season_id and current_ms.is_licensed and (normalized->>'ranking'='' or normalized->>'ranking'=coalesce(current_ms.ranking,''))) then action='unchanged';else action='update';end if;elsif exists(select 1 from public.club_members m where m.last_name_normalized=public.normalize_member_identity(normalized->>'lastName') and m.first_name_normalized=public.normalize_member_identity(normalized->>'firstName') and m.birth_date=(normalized->>'birthDate')::date) then if coalesce((r#>>'{decision,confirmDistinctIdentity}')::boolean,false) then warnings=warnings||'"Identité connue : création distincte confirmée"'::jsonb;action='create';else errors=errors||'"Identité déjà connue sous une autre licence"'::jsonb;action='identity_conflict';end if;end if;
  if jsonb_array_length(errors)>0 and coalesce((r#>>'{decision,ignored}')::boolean,false) then action='ignored';end if;if action='sensitive_warning' and not coalesce((r#>>'{decision,confirmedSensitive}')::boolean,false) and not coalesce((r#>>'{decision,ignored}')::boolean,false) then errors=errors||'"Confirmation sensible manquante"'::jsonb;end if;
  insert into public.club_member_import_rows(import_id,line_number,original_data,normalized_data,planned_action,admin_decision,errors,warnings,detected_member_id,observed_updated_at) values(target.id,(r->>'lineNumber')::int,coalesce(r->'original',r->'data'),normalized,action,coalesce(r->'decision','{}'),errors,warnings,member.id,member.updated_at);
 end loop;update public.club_member_imports i set status=case when exists(select 1 from public.club_member_import_rows ir where ir.import_id=i.id and jsonb_array_length(ir.errors)>0 and ir.planned_action<>'ignored') then 'draft'::public.club_member_import_status else 'validated'::public.club_member_import_status end,validated_at=case when not exists(select 1 from public.club_member_import_rows ir where ir.import_id=i.id and jsonb_array_length(ir.errors)>0 and ir.planned_action<>'ignored') then now() end,error_count=(select count(*) from public.club_member_import_rows ir where ir.import_id=i.id and jsonb_array_length(ir.errors)>0),warning_count=(select count(*) from public.club_member_import_rows ir where ir.import_id=i.id and jsonb_array_length(ir.warnings)>0) where i.id=target.id;end $$;
drop function public.admin_execute_member_import(uuid);
create function public.admin_execute_member_import(target_import_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;r public.club_member_import_rows%rowtype;m public.club_members%rowtype;before_member jsonb;season public.club_seasons%rowtype;was_active boolean;member_unchanged boolean;line_unchanged boolean;season_existed boolean;season_changed boolean;created_n int:=0;updated_n int:=0;reactivated_n int:=0;unchanged_n int:=0;ignored_n int:=0;processing_started boolean:=false;begin
 select * into target from public.club_member_imports where id=target_import_id for update;if target.status<>'validated' then raise exception 'Import déjà exécuté ou non validé' using errcode='55000';end if;if not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select * into season from public.club_seasons where id=target.club_season_id and club_id=target.club_id and is_active for share;if season.id is null then raise exception 'La saison ciblée n’est plus active' using errcode='40001';end if;if exists(select 1 from public.club_member_import_rows where import_id=target.id and planned_action<>'ignored' and jsonb_array_length(errors)>0) then raise exception 'Des erreurs bloquantes restent à résoudre' using errcode='22023';end if;if exists(select 1 from public.club_member_import_rows where import_id=target.id and planned_action<>'ignored' group by normalized_data->>'licenceNumber' having count(*)>1) then raise exception 'Doublons de licence' using errcode='23505';end if;update public.club_member_imports set status='processing',global_error=null where id=target.id;processing_started=true;
 for r in select * from public.club_member_import_rows where import_id=target.id order by line_number loop
  if coalesce((r.admin_decision->>'ignored')::boolean,false) then update public.club_member_import_rows set executed_action='ignored' where id=r.id;ignored_n:=ignored_n+1;continue;end if;select * into m from public.club_members where licence_number_normalized=public.normalize_member_licence(r.normalized_data->>'licenceNumber') for update;before_member=case when m.id is null then null else to_jsonb(m) end;was_active=coalesce(m.is_active,false);member_unchanged=m.id is not null and public.normalize_member_identity(r.normalized_data->>'lastName')=m.last_name_normalized and public.normalize_member_identity(r.normalized_data->>'firstName')=m.first_name_normalized and (r.normalized_data->>'birthDate')::date=m.birth_date and r.normalized_data->>'gender'=m.gender and (r.normalized_data->>'email'='' or r.normalized_data->>'email'=coalesce(m.email,'')) and (r.normalized_data->>'phone'='' or r.normalized_data->>'phone'=coalesce(m.phone,''));select exists(select 1 from public.club_member_seasons sm where sm.club_member_id=m.id and sm.club_season_id=season.id),exists(select 1 from public.club_member_seasons sm where sm.club_member_id=m.id and sm.club_season_id=season.id and (nullif(r.normalized_data->>'ranking','') is not null and nullif(r.normalized_data->>'ranking','') is distinct from sm.ranking or not sm.is_licensed)) into season_existed,season_changed;line_unchanged=member_unchanged and season_existed and not season_changed and not coalesce((r.admin_decision->>'reactivate')::boolean,false);
  if m.id is not null and m.club_id<>target.club_id then raise exception 'Licence d’un autre club ligne %',r.line_number using errcode='42501';end if;if m.id is not null and (r.detected_member_id is distinct from m.id or r.observed_updated_at is distinct from m.updated_at) then raise exception 'Conflit de concurrence ligne %',r.line_number using errcode='40001';end if;
  if m.id is null then if exists(select 1 from public.club_members x where x.last_name_normalized=public.normalize_member_identity(r.normalized_data->>'lastName') and x.first_name_normalized=public.normalize_member_identity(r.normalized_data->>'firstName') and x.birth_date=(r.normalized_data->>'birthDate')::date) and not coalesce((r.admin_decision->>'confirmDistinctIdentity')::boolean,false) then raise exception 'Identité connue ligne %',r.line_number using errcode='23505';end if;insert into public.club_members(club_id,licence_number,last_name,first_name,birth_date,gender,email,phone) values(target.club_id,r.normalized_data->>'licenceNumber',r.normalized_data->>'lastName',r.normalized_data->>'firstName',(r.normalized_data->>'birthDate')::date,r.normalized_data->>'gender',nullif(r.normalized_data->>'email',''),nullif(r.normalized_data->>'phone','')) returning * into m;created_n:=created_n+1;
  elsif member_unchanged and not coalesce((r.admin_decision->>'reactivate')::boolean,false) then if line_unchanged then unchanged_n:=unchanged_n+1;else updated_n:=updated_n+1;end if;
  else if ((r.normalized_data->>'birthDate')::date<>m.birth_date or r.normalized_data->>'gender'<>m.gender) and not coalesce((r.admin_decision->>'confirmedSensitive')::boolean,false) then raise exception 'Confirmation sensible manquante ligne %',r.line_number using errcode='22023';end if;update public.club_members set last_name=coalesce(nullif(r.normalized_data->>'lastName',''),last_name),first_name=coalesce(nullif(r.normalized_data->>'firstName',''),first_name),birth_date=coalesce(nullif(r.normalized_data->>'birthDate','')::date,birth_date),gender=coalesce(nullif(r.normalized_data->>'gender',''),gender),email=coalesce(nullif(r.normalized_data->>'email',''),email),phone=coalesce(nullif(r.normalized_data->>'phone',''),phone),is_active=case when coalesce((r.admin_decision->>'reactivate')::boolean,false) then true else is_active end where id=m.id returning * into m;updated_n:=updated_n+1;if not was_active and m.is_active then reactivated_n:=reactivated_n+1;end if;end if;
  insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,is_licensed,created_by,updated_by) values(m.id,target.club_id,season.id,nullif(r.normalized_data->>'ranking',''),public.member_category(m.birth_date,season.ends_on),true,auth.uid(),auth.uid()) on conflict(club_member_id,club_season_id) do update set ranking=coalesce(excluded.ranking,club_member_seasons.ranking),category=public.member_category(m.birth_date,season.ends_on),is_licensed=true,updated_at=now(),updated_by=auth.uid() where club_member_seasons.ranking is distinct from coalesce(excluded.ranking,club_member_seasons.ranking) or club_member_seasons.category is distinct from public.member_category(m.birth_date,season.ends_on) or not club_member_seasons.is_licensed;insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,import_id,metadata) values(m.id,target.club_id,season.id,auth.uid(),case when before_member is null then 'import_created' when not was_active and m.is_active then 'import_reactivated' when line_unchanged then 'import_unchanged' else 'import_updated' end,before_member,to_jsonb(m),target.id,jsonb_build_object('line',r.line_number,'decision',r.admin_decision));if not season_existed or season_changed then insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,import_id,metadata) select m.id,target.club_id,season.id,auth.uid(),case when season_existed then 'season_updated' else 'season_created' end,null,to_jsonb(sm),target.id,jsonb_build_object('line_number',r.line_number,'confirmed_sensitive',coalesce((r.admin_decision->>'confirmedSensitive')::boolean,false),'reactivate',coalesce((r.admin_decision->>'reactivate')::boolean,false)) from public.club_member_seasons sm where sm.club_member_id=m.id and sm.club_season_id=season.id;end if;update public.club_member_import_rows set executed_action=case when before_member is null then 'created' when line_unchanged then 'unchanged' when not was_active and m.is_active then 'reactivated' else 'updated' end,before_values=before_member,after_values=to_jsonb(m) where id=r.id;
 end loop;update public.club_member_imports set status='completed',executed_at=now(),created_count=created_n,updated_count=updated_n,reactivated_count=reactivated_n,unchanged_count=unchanged_n,ignored_count=ignored_n where id=target.id;return jsonb_build_object('status','completed','created',created_n,'updated',updated_n,'reactivated',reactivated_n,'unchanged',unchanged_n,'ignored',ignored_n);
exception when others then if target.id is not null and processing_started then update public.club_member_imports set status='failed',executed_at=now(),global_error=sqlerrm,created_count=0,updated_count=0,reactivated_count=0,unchanged_count=0 where id=target.id;return jsonb_build_object('status','failed','error',sqlerrm,'created',0,'updated',0,'reactivated',0,'unchanged',0,'ignored',ignored_n);end if;raise;end $$;
create function public.admin_get_member_import(target_import_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;begin select * into target from public.club_member_imports where id=target_import_id;if target.id is null or not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;return jsonb_build_object('import',to_jsonb(target),'rows',coalesce((select jsonb_agg(to_jsonb(r) order by r.line_number) from public.club_member_import_rows r where r.import_id=target.id),'[]'));end $$;

revoke all on function public.admin_list_club_members(jsonb),public.admin_search_members_global(jsonb),public.admin_get_member(uuid),public.admin_update_member(uuid,jsonb,timestamptz,text),public.admin_correct_member_licence(uuid,text,timestamptz,text),public.admin_update_member_season(uuid,uuid,text,boolean,timestamptz,text),public.admin_get_member_import(uuid),public.admin_execute_member_import(uuid) from public;
grant execute on function public.admin_list_club_members(jsonb),public.admin_search_members_global(jsonb),public.admin_get_member(uuid),public.admin_update_member(uuid,jsonb,timestamptz,text),public.admin_correct_member_licence(uuid,text,timestamptz,text),public.admin_update_member_season(uuid,uuid,text,boolean,timestamptz,text),public.admin_get_member_import(uuid),public.admin_execute_member_import(uuid) to authenticated;

-- One round-trip preview dataset. The client may display these matches, but validate/execute
-- independently recalculate every decision.
create function public.admin_find_member_import_matches(payload jsonb)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
  current_club uuid := public.admin_current_club_id();
begin
  if not public.has_club_permission(current_club, 'members.manage') then
    raise exception 'Forbidden' using errcode = '42501';
  end if;
  if jsonb_typeof(payload) <> 'array' or jsonb_array_length(payload) > 10000 then
    raise exception 'Invalid preview payload' using errcode = '22023';
  end if;
  return coalesce((
    with requested as (
      select distinct
        public.normalize_member_licence(value ->> 'licenceNumber') licence,
        public.normalize_member_identity(value ->> 'lastName') last_name,
        public.normalize_member_identity(value ->> 'firstName') first_name,
        nullif(value ->> 'birthDate', '')::date birth_date
      from jsonb_array_elements(payload)
    )
    select jsonb_agg(jsonb_build_object(
      'id', m.id, 'clubId', m.club_id, 'licenceNumber', m.licence_number_normalized,
      'lastName', m.last_name, 'firstName', m.first_name, 'birthDate', m.birth_date,
      'gender', m.gender, 'email', coalesce(m.email, ''), 'phone', coalesce(m.phone, ''),
      'ranking', coalesce(ms.ranking, ''), 'isActive', m.is_active, 'updatedAt', m.updated_at
    ))
    from public.club_members m
    left join public.club_seasons s on s.club_id = m.club_id and s.is_active
    left join public.club_member_seasons ms on ms.club_member_id = m.id and ms.club_season_id = s.id
    where exists (
      select 1 from requested r
      where r.licence = m.licence_number_normalized
         or (r.last_name = m.last_name_normalized and r.first_name = m.first_name_normalized and r.birth_date = m.birth_date)
    )
  ), '[]'::jsonb);
end $$;
revoke all on function public.admin_find_member_import_matches(jsonb) from public;
grant execute on function public.admin_find_member_import_matches(jsonb) to authenticated;

-- Global search is deliberately synthetic: one row/member, active season by default,
-- no contact or birth data in list results, and no unfiltered cross-club dump.
drop function public.admin_search_members_global(jsonb);
create function public.admin_search_members_global(filters jsonb default '{}')
returns table(id uuid,club_id uuid,club_name text,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz,total_count bigint)
language plpgsql stable security definer set search_path = '' as $$
declare requester uuid := public.admin_current_club_id();
begin
  if not (public.has_club_permission(requester, 'members.manage') or public.has_club_permission(requester, 'tournaments.manage')) then
    raise exception 'Forbidden' using errcode = '42501';
  end if;
  if btrim(coalesce(filters ->> 'search', '')) = '' and btrim(coalesce(filters ->> 'licence', '')) = '' and btrim(coalesce(filters ->> 'last_name', '')) = '' and btrim(coalesce(filters ->> 'first_name', '')) = '' and filters ->> 'club_id' is null then
    raise exception 'Un critère de recherche ou un club est obligatoire' using errcode = '22023';
  end if;
  return query
  with selected_season as (
    select m.id member_id, coalesce((filters ->> 'season_id')::uuid, active.id) season_id
    from public.club_members m
    left join lateral (
      select s.id from public.club_seasons s where s.club_id = m.club_id and s.is_active limit 1
    ) active on true
  ), result as (
    select m.*, c.name club_name, ms.ranking, ms.category, coalesce(ms.is_licensed,false) licensed,
      exists(select 1 from public.profiles p where p.member_id=m.id) linked
    from public.club_members m
    join public.clubs c on c.id=m.club_id
    join selected_season ss on ss.member_id=m.id
    left join public.club_member_seasons ms on ms.club_member_id=m.id and ms.club_season_id=ss.season_id
    where (coalesce(filters->>'search','')='' or m.licence_number_normalized like '%'||public.normalize_member_licence(filters->>'search')||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%' or m.first_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%') and (coalesce(filters->>'licence','')='' or m.licence_number_normalized like '%'||public.normalize_member_licence(filters->>'licence')||'%') and (coalesce(filters->>'last_name','')='' or m.last_name_normalized like '%'||public.normalize_member_identity(filters->>'last_name')||'%') and (coalesce(filters->>'first_name','')='' or m.first_name_normalized like '%'||public.normalize_member_identity(filters->>'first_name')||'%')
      and (filters->>'club_id' is null or m.club_id=(filters->>'club_id')::uuid)
      and (filters->>'active' is null or m.is_active=(filters->>'active')::boolean)
      and (filters->>'licensed' is null or coalesce(ms.is_licensed,false)=(filters->>'licensed')::boolean)
      and (filters->>'ranking' is null or ms.ranking=filters->>'ranking')
      and (filters->>'category' is null or ms.category=filters->>'category')
  )
  select r.id,r.club_id,r.club_name,r.licence_number,r.last_name,r.first_name,
    null::date,r.gender,null::text,null::text,r.is_active,r.ranking,r.category,r.licensed,r.linked,r.updated_at,count(*) over()
  from result r order by r.last_name_normalized,r.first_name_normalized
  limit least(greatest(coalesce((filters->>'page_size')::int,25),1),50)
  offset (greatest(coalesce((filters->>'page')::int,1),1)-1)*least(greatest(coalesce((filters->>'page_size')::int,25),1),50);
end $$;
revoke all on function public.admin_search_members_global(jsonb) from public;
grant execute on function public.admin_search_members_global(jsonb) to authenticated;

drop function public.admin_list_member_imports();
create function public.admin_list_member_imports(filters jsonb default '{}')
returns table(id uuid,file_name text,status text,created_at timestamptz,author_name text,club_name text,season_name text,created_count integer,updated_count integer,reactivated_count integer,unchanged_count integer,ignored_count integer,error_count integer,warning_count integer,global_error text,total_count bigint)
language plpgsql stable security definer set search_path = '' as $$
declare current_club uuid := public.admin_current_club_id();
begin
  if not public.has_club_permission(current_club,'members.manage') then raise exception 'Forbidden' using errcode='42501'; end if;
  return query select i.id,i.file_name,i.status::text,i.created_at,coalesce(p.display_name,nullif(concat_ws(' ',p.first_name,p.last_name),''),'Compte'),c.name,s.name,i.created_count,i.updated_count,i.reactivated_count,i.unchanged_count,i.ignored_count,i.error_count,i.warning_count,i.global_error,count(*) over()
  from public.club_member_imports i join public.clubs c on c.id=i.club_id join public.club_seasons s on s.id=i.club_season_id left join public.profiles p on p.id=i.author_id
  where i.club_id=current_club and (filters->>'status' is null or i.status::text=filters->>'status')
  order by i.created_at desc limit least(greatest(coalesce((filters->>'page_size')::int,25),1),100) offset (greatest(coalesce((filters->>'page')::int,1),1)-1)*least(greatest(coalesce((filters->>'page_size')::int,25),1),100);
end $$;
revoke all on function public.admin_list_member_imports(jsonb) from public;
grant execute on function public.admin_list_member_imports(jsonb) to authenticated;

-- Browser roles have read-only policy access where explicitly granted; every write is RPC-only.
revoke insert, update, delete, truncate, references, trigger on public.club_members, public.club_member_seasons, public.club_member_imports, public.club_member_import_rows, public.club_member_audit_log, public.club_member_access_log from anon, authenticated;

-- Final import executor: stable-member and seasonal changes are deliberately independent.
create or replace function public.admin_execute_member_import(target_import_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  target public.club_member_imports%rowtype;
  season public.club_seasons%rowtype;
  r public.club_member_import_rows%rowtype;
  m public.club_members%rowtype;
  before_member jsonb;
  before_season jsonb;
  was_active boolean;
  stable_changed boolean;
  season_existed boolean;
  season_changed boolean;
  actual_action text;
  created_n integer := 0;
  updated_n integer := 0;
  reactivated_n integer := 0;
  unchanged_n integer := 0;
  ignored_n integer := 0;
  processing_started boolean := false;
begin
  select * into target from public.club_member_imports where id=target_import_id for update;
  if target.status <> 'validated' then raise exception 'Import déjà exécuté ou non validé' using errcode='55000'; end if;
  if not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501'; end if;
  select * into season from public.club_seasons where id=target.club_season_id and club_id=target.club_id and is_active for share;
  if season.id is null then raise exception 'La saison ciblée n’est plus active' using errcode='40001'; end if;
  if exists(select 1 from public.club_member_import_rows ir where ir.import_id=target.id and not coalesce((ir.admin_decision->>'ignored')::boolean,false) group by ir.normalized_data->>'licenceNumber' having count(*)>1) then raise exception 'Doublons de licence' using errcode='23505'; end if;
  update public.club_member_imports set status='processing',global_error=null where id=target.id;
  processing_started := true;
  for r in select * from public.club_member_import_rows where import_id=target.id order by line_number loop
    if coalesce((r.admin_decision->>'ignored')::boolean,false) then
      update public.club_member_import_rows set executed_action='ignored' where id=r.id;
      ignored_n := ignored_n+1; continue;
    end if;
    select * into m from public.club_members where licence_number_normalized=public.normalize_member_licence(r.normalized_data->>'licenceNumber') for update;
    if m.id is not null and m.club_id<>target.club_id then raise exception 'Licence d’un autre club ligne %',r.line_number using errcode='42501'; end if;
    if m.id is not null and (r.detected_member_id is distinct from m.id or r.observed_updated_at is distinct from m.updated_at) then raise exception 'Conflit de concurrence ligne %',r.line_number using errcode='40001'; end if;
    if m.id is null and exists(select 1 from public.club_members x where x.last_name_normalized=public.normalize_member_identity(r.normalized_data->>'lastName') and x.first_name_normalized=public.normalize_member_identity(r.normalized_data->>'firstName') and x.birth_date=(r.normalized_data->>'birthDate')::date) and not coalesce((r.admin_decision->>'confirmDistinctIdentity')::boolean,false) then raise exception 'Identité connue ligne %',r.line_number using errcode='23505'; end if;
    before_member := case when m.id is null then null else to_jsonb(m) end;
    was_active := coalesce(m.is_active,false);
    stable_changed := m.id is not null and (
      public.normalize_member_identity(r.normalized_data->>'lastName')<>m.last_name_normalized or
      public.normalize_member_identity(r.normalized_data->>'firstName')<>m.first_name_normalized or
      (r.normalized_data->>'birthDate')::date<>m.birth_date or r.normalized_data->>'gender'<>m.gender or
      (r.normalized_data->>'email'<>'' and r.normalized_data->>'email' is distinct from m.email) or
      (r.normalized_data->>'phone'<>'' and r.normalized_data->>'phone' is distinct from m.phone) or
      (not m.is_active and coalesce((r.admin_decision->>'reactivate')::boolean,false))
    );
    if m.id is not null and ((r.normalized_data->>'birthDate')::date<>m.birth_date or r.normalized_data->>'gender'<>m.gender) and not coalesce((r.admin_decision->>'confirmedSensitive')::boolean,false) then raise exception 'Confirmation sensible manquante ligne %',r.line_number using errcode='22023'; end if;
    if m.id is null then
      insert into public.club_members(club_id,licence_number,last_name,first_name,birth_date,gender,email,phone) values(target.club_id,r.normalized_data->>'licenceNumber',r.normalized_data->>'lastName',r.normalized_data->>'firstName',(r.normalized_data->>'birthDate')::date,r.normalized_data->>'gender',nullif(r.normalized_data->>'email',''),nullif(r.normalized_data->>'phone','')) returning * into m;
      created_n:=created_n+1; actual_action:='created';
    elsif stable_changed then
      update public.club_members set last_name=coalesce(nullif(r.normalized_data->>'lastName',''),last_name),first_name=coalesce(nullif(r.normalized_data->>'firstName',''),first_name),birth_date=coalesce(nullif(r.normalized_data->>'birthDate','')::date,birth_date),gender=coalesce(nullif(r.normalized_data->>'gender',''),gender),email=coalesce(nullif(r.normalized_data->>'email',''),email),phone=coalesce(nullif(r.normalized_data->>'phone',''),phone),is_active=case when coalesce((r.admin_decision->>'reactivate')::boolean,false) then true else is_active end where id=m.id returning * into m;
      if not was_active and m.is_active then reactivated_n:=reactivated_n+1; actual_action:='reactivated'; else updated_n:=updated_n+1; actual_action:='updated'; end if;
    else actual_action:='unchanged'; end if;
    select to_jsonb(ms),true,(ms.ranking is distinct from coalesce(nullif(r.normalized_data->>'ranking',''),ms.ranking) or not ms.is_licensed or ms.category is distinct from public.member_category(m.birth_date,season.ends_on)) into before_season,season_existed,season_changed from public.club_member_seasons ms where ms.club_member_id=m.id and ms.club_season_id=season.id for update;
    season_existed:=coalesce(season_existed,false); season_changed:=coalesce(season_changed,false);
    if not season_existed then
      insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,is_licensed,created_by,updated_by) values(m.id,target.club_id,season.id,nullif(r.normalized_data->>'ranking',''),public.member_category(m.birth_date,season.ends_on),true,auth.uid(),auth.uid());
    elsif season_changed then
      update public.club_member_seasons set ranking=coalesce(nullif(r.normalized_data->>'ranking',''),ranking),category=public.member_category(m.birth_date,season.ends_on),is_licensed=true,updated_at=now(),updated_by=auth.uid() where club_member_id=m.id and club_season_id=season.id;
    end if;
    if before_member is null or stable_changed then
      insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,import_id,metadata) values(m.id,target.club_id,season.id,auth.uid(),case when before_member is null then 'import_created' when actual_action='reactivated' then 'import_reactivated' when actual_action='unchanged' then 'import_unchanged' else 'import_updated' end,before_member,to_jsonb(m),target.id,jsonb_build_object('line_number',r.line_number,'confirmed_sensitive',coalesce((r.admin_decision->>'confirmedSensitive')::boolean,false),'confirm_distinct_identity',coalesce((r.admin_decision->>'confirmDistinctIdentity')::boolean,false),'reactivate',coalesce((r.admin_decision->>'reactivate')::boolean,false)));
    end if;
    if not season_existed or season_changed then
      insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,before_values,after_values,import_id,metadata) select m.id,target.club_id,season.id,auth.uid(),case when season_existed then 'season_updated' else 'season_created' end,before_season,to_jsonb(ms),target.id,jsonb_build_object('line_number',r.line_number,'confirm_distinct_identity',coalesce((r.admin_decision->>'confirmDistinctIdentity')::boolean,false)) from public.club_member_seasons ms where ms.club_member_id=m.id and ms.club_season_id=season.id;
      if not stable_changed and before_member is not null then actual_action:=case when season_existed then 'season_updated' else 'season_created' end; end if;
    elsif not stable_changed and before_member is not null then unchanged_n:=unchanged_n+1; actual_action:='unchanged'; end if;
    update public.club_member_import_rows set executed_action=actual_action,before_values=before_member,after_values=to_jsonb(m) where id=r.id;
  end loop;
  update public.club_member_imports set status='completed',executed_at=now(),created_count=created_n,updated_count=updated_n,reactivated_count=reactivated_n,unchanged_count=unchanged_n,ignored_count=ignored_n where id=target.id;
  return jsonb_build_object('status','completed','created',created_n,'updated',updated_n,'reactivated',reactivated_n,'unchanged',unchanged_n,'ignored',ignored_n);
exception when others then
  if target.id is not null and processing_started then update public.club_member_imports set status='failed',executed_at=now(),global_error=sqlerrm,created_count=0,updated_count=0,reactivated_count=0,unchanged_count=0 where id=target.id; return jsonb_build_object('status','failed','error',sqlerrm,'created',0,'updated',0,'reactivated',0,'unchanged',0,'ignored',ignored_n); end if;
  raise;
end $$;
revoke all on function public.admin_execute_member_import(uuid) from public;
grant execute on function public.admin_execute_member_import(uuid) to authenticated;
