-- PR38: stable global member identity, seasonal licences, audited and atomic administration/imports.
create extension if not exists unaccent with schema extensions;

create function public.normalize_member_licence(value text) returns text
language sql immutable strict set search_path = '' as $$ select upper(regexp_replace(btrim(value), '\s+', '', 'g')) $$;
create function public.normalize_member_identity(value text) returns text
language sql immutable strict set search_path = '' as $$ select upper(regexp_replace(extensions.unaccent(value), '[[:space:]''’\-]+', '', 'g')) $$;
create function public.member_category(birth_date date, season_ends_on date) returns text
language sql immutable strict set search_path = '' as $$
 select case when extract(year from season_ends_on)-extract(year from birth_date)<=9 then 'M10'
 when extract(year from season_ends_on)-extract(year from birth_date)<=11 then 'M12'
 when extract(year from season_ends_on)-extract(year from birth_date)<=13 then 'M14'
 when extract(year from season_ends_on)-extract(year from birth_date)<=15 then 'M16'
 when extract(year from season_ends_on)-extract(year from birth_date)<=18 then 'M19'
 when extract(year from season_ends_on)-extract(year from birth_date)<=21 then 'M22'
 when extract(year from season_ends_on)-extract(year from birth_date)<=44 then 'Senior'
 when extract(year from season_ends_on)-extract(year from birth_date)<=54 then 'Vétéran A/B' else 'Vétéran Senior' end $$;

alter table public.club_members add column licence_number_normalized text;
alter table public.club_members add column last_name_normalized text;
alter table public.club_members add column first_name_normalized text;
update public.club_members set licence_number=btrim(licence_number), licence_number_normalized=public.normalize_member_licence(licence_number), last_name_normalized=public.normalize_member_identity(last_name), first_name_normalized=public.normalize_member_identity(first_name);
do $$ begin
 if exists(select 1 from public.club_members where birth_date is null or gender is null or gender not in ('male','female')) then raise exception 'PR38 migration: complete birth_date and gender before applying'; end if;
 if exists(select 1 from public.club_members group by licence_number_normalized having count(*)>1) then raise exception 'PR38 migration: duplicate normalized licence'; end if;
end $$;
alter table public.club_members alter column birth_date set not null;
alter table public.club_members alter column gender set not null;
alter table public.club_members alter column licence_number_normalized set not null;
alter table public.club_members alter column last_name_normalized set not null;
alter table public.club_members alter column first_name_normalized set not null;
alter table public.club_members add constraint club_members_gender_check check(gender in ('male','female'));
alter table public.club_members add constraint club_members_birth_not_future check(birth_date<=current_date);
alter table public.club_members drop constraint if exists club_members_licence_number_key;
create unique index club_members_licence_normalized_unique on public.club_members(licence_number_normalized);
create index club_members_identity_search on public.club_members(last_name_normalized,first_name_normalized,birth_date);

create function public.sync_member_normalization() returns trigger language plpgsql set search_path='' as $$ begin
 new.licence_number=btrim(new.licence_number);new.licence_number_normalized=public.normalize_member_licence(new.licence_number);new.last_name=btrim(new.last_name);new.first_name=btrim(new.first_name);new.last_name_normalized=public.normalize_member_identity(new.last_name);new.first_name_normalized=public.normalize_member_identity(new.first_name);new.updated_at=now();return new;end $$;
create trigger sync_member_normalization before insert or update of licence_number,last_name,first_name on public.club_members for each row execute function public.sync_member_normalization();

create table public.club_member_seasons(id uuid primary key default gen_random_uuid(),club_member_id uuid not null references public.club_members(id) on delete restrict,club_id uuid not null references public.clubs(id) on delete restrict,club_season_id uuid not null references public.club_seasons(id) on delete restrict,ranking text,category text not null,is_licensed boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),unique(club_member_id,club_season_id));
create unique index club_seasons_id_club_unique on public.club_seasons(id,club_id);
alter table public.club_member_seasons add constraint club_member_season_same_club foreign key(club_season_id,club_id) references public.club_seasons(id,club_id);

-- Create missing conventional historical seasons, then backfill without discarding a member.
insert into public.club_seasons(club_id,name,starts_on,ends_on,is_active)
select distinct m.club_id,replace(m.season,'/','-'),make_date(substring(m.season from '([0-9]{4})')::int,7,1),make_date(substring(m.season from '[0-9]{4}[-/]([0-9]{4})')::int,6,30),false from public.club_members m
where m.season~'^[0-9]{4}[-/][0-9]{4}$' on conflict(club_id,name) do nothing;
insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category)
select m.id,m.club_id,s.id,m.ranking,coalesce(nullif(m.category,''),public.member_category(m.birth_date,s.ends_on)) from public.club_members m join public.club_seasons s on s.club_id=m.club_id and (s.name=m.season or s.name=replace(m.season,'/','-')) on conflict do nothing;
do $$ begin if exists(select 1 from public.club_members m where not exists(select 1 from public.club_member_seasons ms where ms.club_member_id=m.id)) then raise exception 'PR38 migration: historical season could not be deterministically migrated';end if;end $$;
alter table public.club_members drop column ranking,drop column category,drop column season;

create function public.sync_member_season_category() returns trigger language plpgsql security definer set search_path='' as $$ declare dob date;ending date;begin select m.birth_date,s.ends_on into dob,ending from public.club_members m join public.club_seasons s on s.id=new.club_season_id where m.id=new.club_member_id;new.category=public.member_category(dob,ending);new.updated_at=now();new.updated_by=coalesce(auth.uid(),new.updated_by);return new;end $$;
create trigger sync_member_season_category before insert or update on public.club_member_seasons for each row execute function public.sync_member_season_category();

create type public.club_member_import_status as enum('draft','validated','processing','completed','failed','cancelled');
create table public.club_member_imports(id uuid primary key default gen_random_uuid(),club_id uuid not null references public.clubs(id),club_season_id uuid not null references public.club_seasons(id),file_name text not null,file_size integer not null check(file_size between 0 and 5242880),file_hash text not null,encoding text not null check(encoding in ('utf-8','windows-1252')),separator text not null check(separator in (',',';',E'\t')),column_mapping jsonb not null default '{}',options jsonb not null default '{}',status public.club_member_import_status not null default 'draft',author_id uuid not null default auth.uid() references public.profiles(id),created_at timestamptz not null default now(),validated_at timestamptz,executed_at timestamptz,created_count integer not null default 0,updated_count integer not null default 0,reactivated_count integer not null default 0,unchanged_count integer not null default 0,ignored_count integer not null default 0,error_count integer not null default 0,warning_count integer not null default 0,global_error text,unique(club_id,file_hash));
create table public.club_member_import_rows(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.club_member_imports(id) on delete cascade,line_number integer not null,original_data jsonb not null,normalized_data jsonb not null,planned_action text not null,admin_decision jsonb not null default '{}',errors jsonb not null default '[]',warnings jsonb not null default '[]',detected_member_id uuid references public.club_members(id),observed_updated_at timestamptz,executed_action text,before_values jsonb,after_values jsonb,unique(import_id,line_number));
create table public.club_member_audit_log(id uuid primary key default gen_random_uuid(),club_member_id uuid references public.club_members(id) on delete restrict,club_id uuid not null references public.clubs(id),club_season_id uuid references public.club_seasons(id),author_id uuid references public.profiles(id),occurred_at timestamptz not null default now(),action text not null,before_values jsonb,after_values jsonb,import_id uuid references public.club_member_imports(id),reason text,metadata jsonb not null default '{}');
create table public.club_member_access_log(id uuid primary key default gen_random_uuid(),club_member_id uuid not null references public.club_members(id),requesting_club_id uuid not null references public.clubs(id),member_club_id uuid not null references public.clubs(id),accessed_by uuid not null references public.profiles(id),accessed_at timestamptz not null default now());

alter table public.club_member_seasons enable row level security;alter table public.club_member_imports enable row level security;alter table public.club_member_import_rows enable row level security;alter table public.club_member_audit_log enable row level security;alter table public.club_member_access_log enable row level security;
drop policy if exists club_members_admin_all on public.club_members;
create policy club_members_manager_read on public.club_members for select to authenticated using(public.has_club_permission(club_id,'members.manage') or exists(select 1 from public.profiles p where p.id=auth.uid() and p.member_id=club_members.id));
create policy member_seasons_read on public.club_member_seasons for select to authenticated using(public.has_club_permission(club_id,'members.manage') or exists(select 1 from public.profiles p where p.id=auth.uid() and p.member_id=club_member_seasons.club_member_id));
create policy member_imports_manager_read on public.club_member_imports for select to authenticated using(public.has_club_permission(club_id,'members.manage'));
create policy member_import_rows_manager_read on public.club_member_import_rows for select to authenticated using(exists(select 1 from public.club_member_imports i where i.id=import_id and public.has_club_permission(i.club_id,'members.manage')));
create policy member_audit_manager_read on public.club_member_audit_log for select to authenticated using(public.has_club_permission(club_id,'members.manage'));
create policy member_access_own_read on public.club_member_access_log for select to authenticated using(accessed_by=auth.uid());
create function public.admin_list_club_members(filters jsonb default '{}') returns table(id uuid,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz)
language sql stable security definer set search_path='' as $$ with context as(select public.admin_current_club_id() club_id),active_season as(select s.id from public.club_seasons s,context c where s.club_id=c.club_id and s.is_active),q as(select coalesce(filters->>'search','') value)
select m.id,m.licence_number,m.last_name,m.first_name,m.birth_date,m.gender,m.email,m.phone,m.is_active,ms.ranking,ms.category,coalesce(ms.is_licensed,false),exists(select 1 from public.profiles p where p.member_id=m.id),m.updated_at from public.club_members m join context c on c.club_id=m.club_id left join active_season a on true left join public.club_member_seasons ms on ms.club_member_id=m.id and ms.club_season_id=a.id,q where public.has_club_permission(c.club_id,'members.manage') and (q.value='' or m.licence_number_normalized like '%'||public.normalize_member_licence(q.value)||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(q.value)||'%' or m.first_name_normalized like '%'||public.normalize_member_identity(q.value)||'%') and (coalesce(filters->>'active','all')='all' or m.is_active=(filters->>'active')::boolean) and (coalesce(filters->>'licensed','all')='all' or coalesce(ms.is_licensed,false)=(filters->>'licensed')::boolean) order by m.last_name_normalized,m.first_name_normalized limit least(coalesce((filters->>'page_size')::int,50),100) offset (greatest(coalesce((filters->>'page')::int,1),1)-1)*least(coalesce((filters->>'page_size')::int,50),100) $$;

create function public.admin_create_member(payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$ declare club uuid:=public.admin_current_club_id();season public.club_seasons%rowtype;result uuid;begin
 if not public.has_club_permission(club,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select * into season from public.club_seasons s where s.club_id=club and s.is_active for share;if season.id is null then raise exception 'Aucune saison active' using errcode='22023';end if;
 if exists(select 1 from public.club_members m where m.last_name_normalized=public.normalize_member_identity(payload->>'lastName') and m.first_name_normalized=public.normalize_member_identity(payload->>'firstName') and m.birth_date=(payload->>'birthDate')::date) then raise exception 'Une identité similaire existe déjà' using errcode='23505';end if;
 insert into public.club_members(club_id,licence_number,last_name,first_name,birth_date,gender,email,phone,is_active) values(club,payload->>'licenceNumber',payload->>'lastName',payload->>'firstName',(payload->>'birthDate')::date,payload->>'gender',nullif(payload->>'email',''),nullif(payload->>'phone',''),true) returning id into result;
 insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,created_by,updated_by) values(result,club,season.id,nullif(payload->>'ranking',''),public.member_category((payload->>'birthDate')::date,season.ends_on),auth.uid(),auth.uid());insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,after_values) values(result,club,season.id,auth.uid(),'manual_created',payload);return result;end $$;

create function public.admin_set_member_active(target_member_id uuid,target_active boolean,expected_updated_at timestamptz,reason text) returns void language plpgsql security definer set search_path='' as $$ declare old public.club_members%rowtype;begin select * into old from public.club_members where id=target_member_id for update;if old.id is null or not public.has_club_permission(old.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;if old.updated_at<>expected_updated_at then raise exception 'La fiche a changé' using errcode='40001';end if;if btrim(coalesce(reason,''))='' then raise exception 'Motif obligatoire' using errcode='22023';end if;update public.club_members set is_active=target_active,updated_at=now() where id=old.id;insert into public.club_member_audit_log(club_member_id,club_id,author_id,action,before_values,after_values,reason) values(old.id,old.club_id,auth.uid(),case when target_active then 'reactivated' else 'deactivated' end,to_jsonb(old),jsonb_build_object('is_active',target_active),reason);end $$;

create function public.admin_search_members_global(filters jsonb default '{}') returns table(id uuid,licence_number text,last_name text,first_name text,birth_date date,gender text,email text,phone text,is_active boolean,ranking text,category text,is_licensed boolean,linked_account boolean,updated_at timestamptz) language plpgsql stable security definer set search_path='' as $$ declare requester uuid:=public.admin_current_club_id();begin if not(public.has_club_permission(requester,'members.manage') or public.has_club_permission(requester,'tournaments.manage')) then raise exception 'Forbidden' using errcode='42501';end if;return query select m.id,m.licence_number,m.last_name,m.first_name,m.birth_date,m.gender,m.email,m.phone,m.is_active,ms.ranking,ms.category,coalesce(ms.is_licensed,false),exists(select 1 from public.profiles p where p.member_id=m.id),m.updated_at from public.club_members m left join public.club_member_seasons ms on ms.club_member_id=m.id and (filters->>'season_id' is null or ms.club_season_id=(filters->>'season_id')::uuid) where coalesce(filters->>'search','')='' or m.licence_number_normalized like '%'||public.normalize_member_licence(filters->>'search')||'%' or m.last_name_normalized like '%'||public.normalize_member_identity(filters->>'search')||'%' order by m.last_name_normalized limit least(coalesce((filters->>'page_size')::int,50),100);end $$;

create function public.admin_create_member_import(payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$ declare club uuid:=public.admin_current_club_id();season uuid;result uuid;begin if not public.has_club_permission(club,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select id into season from public.club_seasons where club_id=club and is_active;if season is null then raise exception 'Aucune saison active' using errcode='22023';end if;insert into public.club_member_imports(club_id,club_season_id,file_name,file_size,file_hash,encoding,separator,column_mapping,options) values(club,season,payload->>'file_name',(payload->>'file_size')::int,payload->>'file_hash',payload->>'encoding',payload->>'separator',coalesce(payload->'mapping','{}'),coalesce(payload->'options','{}')) returning id into result;return result;end $$;
create function public.admin_validate_member_import(target_import_id uuid,rows jsonb) returns void language plpgsql security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;begin select * into target from public.club_member_imports where id=target_import_id for update;if target.status<>'draft' or not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Import non modifiable' using errcode='42501';end if;if jsonb_array_length(rows)>10000 then raise exception 'Trop de lignes' using errcode='22023';end if;insert into public.club_member_import_rows(import_id,line_number,original_data,normalized_data,planned_action,admin_decision,errors,warnings,detected_member_id,observed_updated_at) select target.id,(r->>'lineNumber')::int,coalesce(r->'original','{}'),r->'data',r->>'action',coalesce(r->'decision','{}'),coalesce(r->'errors','[]'),coalesce(r->'warnings','[]'),nullif(r->>'memberId','')::uuid,nullif(r->>'observedUpdatedAt','')::timestamptz from jsonb_array_elements(rows) r;update public.club_member_imports set status='validated',validated_at=now(),error_count=(select count(*) from public.club_member_import_rows where import_id=target.id and jsonb_array_length(errors)>0),warning_count=(select count(*) from public.club_member_import_rows where import_id=target.id and jsonb_array_length(warnings)>0) where id=target.id;end $$;
create function public.admin_execute_member_import(target_import_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare target public.club_member_imports%rowtype;r public.club_member_import_rows%rowtype;m public.club_members%rowtype;season public.club_seasons%rowtype;created_n int:=0;updated_n int:=0;reactivated_n int:=0;ignored_n int:=0;begin
 select * into target from public.club_member_imports where id=target_import_id for update;if target.status<>'validated' then raise exception 'Import déjà exécuté ou non validé' using errcode='55000';end if;if not public.has_club_permission(target.club_id,'members.manage') then raise exception 'Forbidden' using errcode='42501';end if;select * into season from public.club_seasons where id=target.club_season_id and club_id=target.club_id and is_active for share;if season.id is null then raise exception 'La saison ciblée n’est plus active' using errcode='40001';end if;if exists(select 1 from public.club_member_import_rows where import_id=target.id and executed_action is null and jsonb_array_length(errors)>0 and not coalesce((admin_decision->>'ignored')::boolean,false)) then raise exception 'Des erreurs bloquantes restent à résoudre' using errcode='22023';end if;if exists(select 1 from public.club_member_import_rows where import_id=target.id and not coalesce((admin_decision->>'ignored')::boolean,false) group by normalized_data->>'licenceNumber' having count(*)>1) then raise exception 'Doublons de licence dans le fichier' using errcode='23505';end if;update public.club_member_imports set status='processing' where id=target.id;
 for r in select * from public.club_member_import_rows where import_id=target.id order by line_number loop
  if coalesce((r.admin_decision->>'ignored')::boolean,false) then update public.club_member_import_rows set executed_action='ignored' where id=r.id;ignored_n:=ignored_n+1;continue;end if;
  select * into m from public.club_members where licence_number_normalized=public.normalize_member_licence(r.normalized_data->>'licenceNumber') for update;
  if m.id is not null and m.club_id<>target.club_id then raise exception 'Licence appartenant à un autre club (ligne %)',r.line_number using errcode='42501';end if;
  if m.id is not null and r.observed_updated_at is not null and m.updated_at<>r.observed_updated_at then raise exception 'Conflit de concurrence ligne %',r.line_number using errcode='40001';end if;
  if m.id is null then insert into public.club_members(club_id,licence_number,last_name,first_name,birth_date,gender,email,phone) values(target.club_id,r.normalized_data->>'licenceNumber',r.normalized_data->>'lastName',r.normalized_data->>'firstName',(r.normalized_data->>'birthDate')::date,r.normalized_data->>'gender',nullif(r.normalized_data->>'email',''),nullif(r.normalized_data->>'phone','')) returning * into m;created_n:=created_n+1;
  else update public.club_members set last_name=coalesce(nullif(r.normalized_data->>'lastName',''),last_name),first_name=coalesce(nullif(r.normalized_data->>'firstName',''),first_name),birth_date=coalesce(nullif(r.normalized_data->>'birthDate','')::date,birth_date),gender=coalesce(nullif(r.normalized_data->>'gender',''),gender),email=coalesce(nullif(r.normalized_data->>'email',''),email),phone=coalesce(nullif(r.normalized_data->>'phone',''),phone),is_active=case when coalesce((r.admin_decision->>'reactivate')::boolean,false) then true else is_active end where id=m.id returning * into m;updated_n:=updated_n+1;if not m.is_active and coalesce((r.admin_decision->>'reactivate')::boolean,false) then reactivated_n:=reactivated_n+1;end if;end if;
  insert into public.club_member_seasons(club_member_id,club_id,club_season_id,ranking,category,created_by,updated_by) values(m.id,target.club_id,season.id,nullif(r.normalized_data->>'ranking',''),public.member_category(m.birth_date,season.ends_on),auth.uid(),auth.uid()) on conflict(club_member_id,club_season_id) do update set ranking=coalesce(nullif(excluded.ranking,''),club_member_seasons.ranking),is_licensed=true,updated_at=now(),updated_by=auth.uid();
  insert into public.club_member_audit_log(club_member_id,club_id,club_season_id,author_id,action,after_values,import_id,metadata) values(m.id,target.club_id,season.id,auth.uid(),case when r.planned_action='create' then 'import_created' else 'import_updated' end,to_jsonb(m),target.id,jsonb_build_object('line',r.line_number,'decision',r.admin_decision));update public.club_member_import_rows set executed_action=case when r.planned_action='create' then 'created' else 'updated' end,after_values=to_jsonb(m) where id=r.id;
 end loop;update public.club_member_imports set status='completed',executed_at=now(),created_count=created_n,updated_count=updated_n,reactivated_count=reactivated_n,ignored_count=ignored_n where id=target.id;
exception when others then if target.id is not null then update public.club_member_imports set status='failed',executed_at=now(),global_error=sqlerrm where id=target.id;end if;end $$;

create function public.is_active_licensee(target_profile_id uuid,target_date date default current_date) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles p left join public.club_members m on m.id=p.member_id where p.id=target_profile_id and ((m.is_active and exists(select 1 from public.club_seasons s join public.club_member_seasons ms on ms.club_season_id=s.id and ms.club_member_id=m.id where s.club_id=m.club_id and s.is_active and ms.is_licensed)) or (p.member_id is null and p.membership_status='active'::public.membership_status and p.membership_validated_at is not null and p.membership_validated_by is not null and (p.membership_valid_until is null or p.membership_valid_until>=target_date)))) $$;
create or replace function public.find_member_by_licence(licence_number text,last_name text,first_name text,birth_date date) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.club_members m where m.licence_number_normalized=public.normalize_member_licence(licence_number) and m.last_name_normalized=public.normalize_member_identity(last_name) and m.first_name_normalized=public.normalize_member_identity(first_name) and m.birth_date=find_member_by_licence.birth_date) $$;

revoke all on function public.normalize_member_licence(text),public.normalize_member_identity(text),public.member_category(date,date),public.admin_list_club_members(jsonb),public.admin_create_member(jsonb),public.admin_set_member_active(uuid,boolean,timestamptz,text),public.admin_search_members_global(jsonb),public.admin_create_member_import(jsonb),public.admin_validate_member_import(uuid,jsonb),public.admin_execute_member_import(uuid) from public;
grant execute on function public.admin_list_club_members(jsonb),public.admin_create_member(jsonb),public.admin_set_member_active(uuid,boolean,timestamptz,text),public.admin_search_members_global(jsonb),public.admin_create_member_import(jsonb),public.admin_validate_member_import(uuid,jsonb),public.admin_execute_member_import(uuid) to authenticated;
comment on table public.club_members is 'Stable global person identity and current club; contact email is never an Auth login address.';
comment on table public.club_member_seasons is 'Annual licence truth and immutable historical represented club.';
create function public.admin_list_member_imports() returns setof public.club_member_imports language sql stable security definer set search_path='' as $$ select i.* from public.club_member_imports i where public.has_club_permission(i.club_id,'members.manage') and i.club_id=public.admin_current_club_id() order by i.created_at desc $$;
revoke all on function public.admin_list_member_imports() from public;grant execute on function public.admin_list_member_imports() to authenticated;

create or replace function public.link_profile_to_member(licence_number text,last_name text,first_name text,birth_date date) returns uuid language plpgsql security definer set search_path='' as $$ declare profile uuid:=auth.uid();member uuid;other uuid;begin if profile is null then raise exception 'Authentication required' using errcode='42501';end if;select m.id into member from public.club_members m where m.licence_number_normalized=public.normalize_member_licence(licence_number) and m.last_name_normalized=public.normalize_member_identity(last_name) and m.first_name_normalized=public.normalize_member_identity(first_name) and m.birth_date=link_profile_to_member.birth_date for update;if member is null then raise exception 'Member identity does not match the club licence registry' using errcode='P0002';end if;select p.id into other from public.profiles p where p.member_id=member;if other is not null and other<>profile then raise exception 'Licence is already linked to another account' using errcode='23505';end if;perform set_config('app.allow_profile_member_link','on',true);update public.profiles set member_id=member,updated_at=now() where id=profile;if not found then raise exception 'Current profile not found' using errcode='P0002';end if;return member;end $$;
revoke all on function public.link_profile_to_member(text,text,text,date) from public;grant execute on function public.link_profile_to_member(text,text,text,date) to authenticated;
